const SEARCH_INDEX = [
  // ── スタッフ紹介 ──
  {"title":"岡本 洋史 先生","url":"pages/staff-okamoto.html","desc":"ICU部長 集中治療専門医","keywords":"岡本洋史 おかもと ICU部長 集中治療専門医 スタッフ紹介"},
  {"title":"青木 和裕 先生","url":"pages/staff-aoki.html","desc":"スタッフ医師 集中治療科","keywords":"青木和裕 あおき スタッフ医師 スタッフ紹介"},
  {"title":"岡野 弘 先生","url":"pages/staff-okano.html","desc":"スタッフ医師 集中治療科","keywords":"岡野弘 おかの スタッフ医師 スタッフ紹介"},
  {"title":"後藤 俊作 先生","url":"pages/staff-goto.html","desc":"スタッフ医師 集中治療科","keywords":"後藤俊作 ごとう スタッフ医師 スタッフ紹介"},
  {"title":"宮﨑 令奈 先生","url":"pages/staff-miyazaki.html","desc":"スタッフ医師 集中治療科","keywords":"宮﨑令奈 みやざき スタッフ医師 スタッフ紹介"},
  {"title":"関谷 智 先生","url":"pages/staff-sekiya.html","desc":"スタッフ医師 集中治療科","keywords":"関谷智 せきや スタッフ医師 スタッフ紹介"},

  // ── ICUコアカン ──
  {"title":"ICUコアカン","url":"pages/icu-core-conf.html","desc":"ICUコアカンファレンス一覧","keywords":"コアカン カンファレンス 学習 プレゼンテーション By System 透析"},
  {"title":"注目論文・最新ガイドラインまとめ","url":"pages/articles-guidelines.html","desc":"ICU関連の注目論文や最新ガイドラインの要約","keywords":"論文 ガイドライン エビデンス 文献 レビュー 最新"},
  {"title":"論文まとめ：神経系","url":"pages/articles-guidelines.html#art-neuro","desc":"神経系の注目論文・ガイドライン","keywords":"神経 脳 意識障害 TTM 心停止"},
  {"title":"AHA/ASA 2023 くも膜下出血（aSAH）管理ガイドライン","url":"pages/articles-gl-sah2023.html","desc":"AHA/ASA 2023年版aSAHガイドライン — 診断・再出血予防・血管攣縮・DCI・水頭症・痙攣・リハビリの推奨まとめ","keywords":"くも膜下出血 SAH aSAH subarachnoid hemorrhage 動脈瘤 aneurysm DCI delayed cerebral ischemia 脳血管攣縮 vasospasm ニモジピン nimodipine TCD transcranial Doppler EVD 脳室ドレナージ 水頭症 hydrocephalus 痙攣 seizure レベチラセタム クリッピング コイル塞栓 ISAT 再出血 トラネキサム酸 TXA 血圧管理 HH grade WFNS Hunt-Hess 雷鳴頭痛 thunderclap headache Ottawa SAH rule CT LP 腰椎穿刺 CTA DSA 高ボリューム施設 多職種 リハビリ 認知機能 MoCA AHA ASA Stroke 2023 Hoh"},
  {"title":"アルコール離脱症候群（AWS）神経集中治療における評価と治療（Neurocrit Care 2021）","url":"pages/articles-gl-aws-ncc2021.html","desc":"神経集中治療患者におけるAWSの評価ツール（CIWA-Ar・MINDS・BAL）と治療（BZD・フェノバルビタール・DEX・バルプロ酸・ガバペンチン・ケタミン）の包括的レビュー","keywords":"アルコール離脱 alcohol withdrawal AWS DTs delirium tremens 振戦せん妄 CIWA CIWA-Ar MINDS 評価スコア BAL 血中アルコール PAWSS ベンゾジアゼピン benzodiazepine ミダゾラム midazolam ロラゼパム lorazepam ジアゼパム diazepam フェノバルビタール phenobarbital デクスメデトミジン dexmedetomidine バルプロ酸 valproic acid VPA ガバペンチン gabapentin バクロフェン baclofen カルバマゼピン carbamazepine ケタミン ketamine プロポフォール propofol YAWP 症状連動 symptom-triggered 神経集中治療 neurocritical care 離脱痙攣 withdrawal seizure チアミン thiamine ウェルニッケ Wernicke PSH paroxysmal sympathetic hyperactivity TBI 外傷性脳障害 Neurocritical Care Farrokh 2021"},
  {"title":"AWS — 評価ツール（CIWA-Ar・MINDS・BAL）","url":"pages/articles-gl-aws-ncc2021.html#aws-assessment","desc":"CIWA-Ar（10項目・最大67点）とMINDS（9項目・最大46点）の比較。入院時BALによるリスク層別（>200 mg/dL：30倍リスク）","keywords":"CIWA-Ar MINDS BAL 血中アルコール濃度 評価スコア PAWSS 93.1 PPV 99.5 NPV 神経集中治療 リスク予測"},
  {"title":"AWS — ベンゾジアゼピン療法・YAWPプロトコル","url":"pages/articles-gl-aws-ncc2021.html#aws-bzd","desc":"症状連動ミダゾラムベースのYAWPアルゴリズム。各BZD製剤の薬物動態比較と神経集中治療での注意点","keywords":"YAWP ミダゾラム midazolam ロラゼパム lorazepam ジアゼパム diazepam クロルジアゼポキシド 症状連動 symptom-triggered 半減期 プロピレングリコール"},
  {"title":"ACNS 標準クリティカルケアEEG用語集 2021年版","url":"pages/articles-gl-acns-eeg2021.html","desc":"ICU脳波判読のための標準用語集 — EEG背景波・散発性てんかん型放電・RPPs・電気的発作・BIRDs・IIC・最低限記録要件","keywords":"EEG 脳波 クリティカルケア critical care 連続EEGモニタリング cEEG RPPs rhythmic periodic patterns PDs periodic discharges LPDs GPDs BIPDs RDA rhythmic delta activity LRDA GRDA SW spike wave てんかん型放電 epileptiform discharges BIRDs brief potentially ictal rhythmic discharges IIC ictal-interictal continuum ESz electrographic seizure ESE electrographic status epilepticus ECSz electroclinical seizure ECSE Burst suppression バースト抑制 CAPE cyclic alternating pattern encephalopathy Extreme Delta Brush EDB 抗NMDA受容体脳炎 Plus modifier SIRPIDs 刺激誘発 対称性 continuity 連続性 反応性 reactivity ザルツブルク基準 Salzburg 電気的てんかん重積 非けいれん性てんかん重積 NCSE Hirsch ACNS J Clin Neurophysiol 2021"},
  {"title":"ACNS EEG用語 — A. EEG背景波（対称性・連続性・反応性・CAPE）","url":"pages/articles-gl-acns-eeg2021.html#eeg-background","desc":"対称性・背景周波数・後頭部優位律動・連続性（Burst-suppression）・反応性・State Changes・CAPE・電位・AP勾配・ブリーチ効果","keywords":"EEG背景波 対称性 symmetry 背景周波数 posterior dominant rhythm alpha rhythm 連続性 continuity burst suppression attenuation suppression 反応性 reactivity SIRPIDs state changes CAPE cyclic alternating encephalopathy 電位 voltage AP gradient breach effect ブリーチ"},
  {"title":"ACNS EEG用語 — B. 散発性てんかん型放電（スパイク・鋭波・ポリスパイク）","url":"pages/articles-gl-acns-eeg2021.html#sporadic-eds","desc":"スパイク（20〜70ms）・鋭波（70〜200ms）・ポリスパイクの定義と出現頻度（Abundant/Frequent/Occasional/Rare）","keywords":"散発性てんかん型放電 sporadic epileptiform discharges スパイク spike 鋭波 sharp wave ポリスパイク polyspike Abundant Frequent Occasional Rare 出現頻度"},
  {"title":"ACNS EEG用語 — C. RPPs（PDs・RDA・SW・Plusモディファイア・EDB）","url":"pages/articles-gl-acns-eeg2021.html#rpps","desc":"G/L/BI/UI/Mf × PDs/RDA/SW の命名体系。Evolving/Fluctuating/Static・Plus（＋F/R/S）・Extreme Delta Brush","keywords":"RPPs rhythmic periodic patterns PDs periodic discharges LPDs GPDs BIPDs UIPDs RDA rhythmic delta activity LRDA GRDA BIRDA SW spike wave Generalized Lateralized Bilateral Independent Unilateral Independent Multifocal Plus modifier fast rhythmic sharp EDB extreme delta brush evolving fluctuating static prevalence duration frequency sharpness voltage stimulus-induced SI ST SIRPIDs"},
  {"title":"ACNS EEG用語 — D. 電気的・電気臨床的発作（ESz・ESE・ECSz・ECSE）","url":"pages/articles-gl-acns-eeg2021.html#seizures","desc":"ESz（EDs ＞2.5Hz/10秒 またはevolution≥10秒）・ESE（連続≥10分または60分の≥20%）・ECSz・ECSE・Possible ECSEの定義","keywords":"電気的発作 electrographic seizure ESz ESE electrographic status epilepticus ECSz electroclinical seizure ECSE possible ECSE てんかん重積 status epilepticus ザルツブルク Salzburg criteria evolution 10秒 20% 60分 NCSE 非けいれん"},
  {"title":"ACNS EEG用語 — E. BIRDs / F. IIC","url":"pages/articles-gl-acns-eeg2021.html#birds","desc":"BIRDs（＞4Hz・0.5〜10秒）とIIC（possible ESz：PDs/SW 1〜2.5Hz、または側在性RDA ＞1Hz＋Plus）の定義","keywords":"BIRDs brief potentially ictal rhythmic discharges IIC ictal-interictal continuum possible ESz possible NCSE GPFA paroxysmal fast activity evolving birds definite possible 側在性 LRDA BIRDA UIRDA Plus modifier fluctuation"},
  {"title":"AWS — 代替薬・補助薬（フェノバルビタール・DEX・バルプロ酸等）","url":"pages/articles-gl-aws-ncc2021.html#aws-alternatives","desc":"BZD難治性AWSへの補助薬：フェノバルビタール・デクスメデトミジン・バルプロ酸・ガバペンチン・ケタミン・プロポフォールの利点と欠点","keywords":"フェノバルビタール phenobarbital デクスメデトミジン dexmedetomidine バルプロ酸 valproic acid ガバペンチン gabapentin ケタミン ketamine プロポフォール propofol バクロフェン baclofen カルバマゼピン carbamazepine BZD難治 BZD refractory"},
  {"title":"論文まとめ：循環器系","url":"pages/articles-guidelines.html#art-cardio","desc":"循環器系の注目論文・ガイドライン","keywords":"循環 ショック 昇圧薬 心不全"},
  {"title":"ERC-ESICM 2021 心拍再開後管理（PCAS）ガイドライン","url":"pages/articles-gl-pcas-erc2021.html","desc":"心停止後症候群（PCAS）の包括的管理 — TTM・神経予後予測・冠動脈再灌流・血行動態管理のまとめ","keywords":"PCAS 心停止後症候群 post-cardiac arrest syndrome ROSC 心拍再開 心停止 cardiac arrest 体温管理療法 TTM targeted temperature management 神経予後予測 neuroprognostication NSE 神経特異エノラーゼ SSEP 体性感覚誘発電位 N20 EEG 脳波 burst suppression 瞳孔反射 status myoclonus 頭部CT GWR PCI 冠動脈再灌流 MAP 低血圧 ノルアドレナリン ドブタミン ICD 心蘇生 認知障害 長期転帰 臓器提供 DCD WLST 治療中止 ERC ESICM Nolan Intensive Care Med 2021"},
  {"title":"ERC-ESICM PCAS — S1 PCAS概念と初期管理","url":"pages/articles-gl-pcas-erc2021.html#pcas-overview","desc":"Post-Cardiac Arrest Syndromeの4要素と心停止原因の診断戦略","keywords":"PCAS 心停止後症候群 脳障害 心筋機能障害 虚血再灌流 原因診断 CAG PCI STEMI CT脳 心停止センター"},
  {"title":"ERC-ESICM PCAS — S2 呼吸管理","url":"pages/articles-gl-pcas-erc2021.html#respiratory","desc":"ROSC後の酸素目標（SpO₂ 94–98%）・PaCO₂管理・肺保護換気","keywords":"SpO₂ 94 98 PaO₂ 酸素目標 過酸素血症 低酸素血症 PaCO₂ 換気管理 肺保護 tidal volume 一回換気量 ROSC"},
  {"title":"ERC-ESICM PCAS — S3 循環管理","url":"pages/articles-gl-pcas-erc2021.html#hemodynamics","desc":"PCI適応・MAP目標・昇圧薬・心エコー・機械的循環補助","keywords":"MAP 65 低血圧 ノルアドレナリン ドブタミン 心エコー 乳酸 IABP Impella VA-ECMO 機械的循環補助 CAG PCI COACT"},
  {"title":"ERC-ESICM PCAS — S4 神経系管理","url":"pages/articles-gl-pcas-erc2021.html#neuro-mgmt","desc":"痙攣管理（レベチラセタム・バルプロ酸）と体温管理療法（TTM 32–36°C）","keywords":"けいれん 痙攣 ミオクローヌス レベチラセタム バルプロ酸 TTM 32 33 36 体温管理 発熱 シバリング Lance Adams EEG"},
  {"title":"ERC-ESICM PCAS — S6 神経学的予後予測","url":"pages/articles-gl-pcas-erc2021.html#prognostication","desc":"マルチモーダル予後予測：臨床診察・EEG・SSEP・NSE・頭部画像","keywords":"神経予後 予後予測 neuroprognostication マルチモーダル 瞳孔反射 角膜反射 SSEP N20 EEG burst suppression suppression NSE 60 GWR MRI ADC status myoclonus WLST 自己成就予言"},
  {"title":"AHA/NCS 2024 心停止後の集中治療管理 科学的声明","url":"pages/articles-gl-pcas-aha2024.html","desc":"AHA・NCS共同コンセンサス声明 — 心停止後ICU管理（体温管理・神経予後予測除く）の専門家コンセンサス声明","keywords":"PCAS 心停止後 post cardiac arrest MAP 80 autoregulation MAPOPT ICP 脳浮腫 EEG cEEG 72 120時間 痙攣 てんかん重積 SE IIC 発作間欠期連続体 ミオクローヌス myoclonus バルプロ酸 レベチラセタム クロナゼパム 鎮静 プロポフォール レミフェンタニル フェンタニル 短時間作用性 NMB 筋弛緩 早期CAG STEMI 非ST上昇 エコー 心エコー 機械的循環補助 MCS ECMO 肺保護換気 SpO₂ 92 98 PaCO₂ DVT LMWH 低分子ヘパリン 輸血 Hb 7 9 経腸栄養 栄養 EN trophic PN 経験的抗菌薬 CRP PCT 血糖 81 180 ステロイド 副腎 重炭酸ナトリウム RRT 定量的瞳孔計測 Quantitative Pupillometry Hirsch Geocadin AHA NCS Circulation 2024"},
  {"title":"AHA/NCS PCAS — 脳灌流・酸素化・ICP","url":"pages/articles-gl-pcas-aha2024.html#aha-s1","desc":"MAP >80 mmHg目標・MAPOPT・ICP侵襲的モニタリング・Hb >7・SpO₂ 92–98%","keywords":"MAP 80 MAPOPT autoregulation cerebrovascular 脳灌流圧 CPP ICP 脳浮腫 brain edema 侵襲的モニタリング pressure reactivity index 近赤外分光 NIRS TCD Hb 7 SpO₂ 92 98"},
  {"title":"AHA/NCS PCAS — EEG・痙攣・IIC","url":"pages/articles-gl-pcas-aha2024.html#aha-s2","desc":"cEEG 72–120時間・SE治療（burst suppression ≥24h）・バルプロ酸・レベチラセタム・散発性放電は治療しない","keywords":"EEG cEEG 72 120時間 痙攣 seizure てんかん重積 status epilepticus SE IIC 発作間欠期連続体 ictal-interictal continuum ミオクローヌス myoclonus 電気臨床的 electroclinical burst suppression バルプロ酸 valproic acid レベチラセタム levetiracetam クロナゼパム clonazepam 散発性放電 sporadic epileptiform discharges"},
  {"title":"AHA/NCS PCAS — 鎮静・早期トリアージ","url":"pages/articles-gl-pcas-aha2024.html#aha-s3","desc":"短時間作用性鎮静（プロポフォール・レミフェンタニル）推奨・早期リスク層別化は治療中止根拠にしない","keywords":"鎮静 sedation プロポフォール propofol レミフェンタニル remifentanil フェンタニル fentanyl ミダゾラム midazolam モルヒネ morphine NMB 筋弛緩 早期トリアージ early triage life support 治療中止 prognostication 覚醒 awakening"},
  {"title":"AHA/NCS PCAS — 心臓・循環管理","url":"pages/articles-gl-pcas-aha2024.html#aha-s4","desc":"早期エコー・MAP個別化・難治性ショックへのMCS・非ST上昇でも早期CAGを検討","keywords":"心エコー echocardiography MAP 80 inotrope vasopressor lactate ScvO₂ 乳酸 IABP LVAD RVAD ECMO MCS 機械的循環補助 CAG 冠動脈造影 STEMI 非ST上昇 COACT ARREST PEARL EMERGE PCI 冠動脈"},
  {"title":"AHA/NCS PCAS — 呼吸・血液・栄養・感染症","url":"pages/articles-gl-pcas-aha2024.html#aha-s5","desc":"肺保護換気・SpO₂ 92–98%・Hb閾値・DVT予防LMWH・早期EN・CRP/PCT不使用","keywords":"肺保護換気 lung protective ventilation ARDS tidal volume 一回換気量 SpO₂ 92 98 FiO₂ PaCO₂ DVT 深部静脈血栓症 LMWH 低分子ヘパリン Hb 7 9 輸血 RBCT EN 経腸栄養 trophic PN 経静脈栄養 CRP PCT 抗菌薬 経験的 prophylactic antibiotic"},
  {"title":"論文まとめ：呼吸器系","url":"pages/articles-guidelines.html#art-resp","desc":"呼吸器系の注目論文・ガイドライン","keywords":"呼吸 ARDS 人工呼吸 PEEP"},
  {"title":"インスピロンネブライザー完全ガイド（看護学雑誌 2008）","url":"pages/articles-gl-inspiron2008.html","desc":"ベンチュリ管の原理・O₂濃度調節・流量・気道加湿の解説","keywords":"インスピロン ネブライザー ベンチュリ ベルヌーイ 酸素療法 O2濃度 流量 加湿 相対湿度 絶対湿度 飽和水蒸気量 結露 ヒュミディファイヤー エアロゾル 粒子径 アキュロックス ダイリューター PEEP弁 看護学雑誌 2008"},
  {"title":"論文まとめ：腎・電解質系","url":"pages/articles-guidelines.html#art-renal","desc":"腎・電解質系の注目論文・ガイドライン","keywords":"腎 AKI RRT 電解質 透析"},
  {"title":"アルブミン vs 非投与（CHEST 2025）— 敗血症性ショック+腎障害患者のRRT・死亡率","url":"pages/articles-gl-albumin-sepsis2025.html","desc":"米国220病院9,988例の後ろ向きIPTWコホート研究 — 25%アルブミンがRRT・院内死亡リスクを増加","keywords":"アルブミン albumin 敗血症性ショック septic shock 腎障害 renal impairment AKI RRT 腎代替療法 院内死亡 mortality 25%アルブミン 高張性 hyperoncotic 5%アルブミン 等張性 iso-oncotic IPTW コホート PINC AI CHEST 2025 Patanwala 糸球体 惨透圧 循環過負荷 MAKE KDIGO Stage3 eGFR クレアチニン"},
  {"title":"アルブミン研究 S1〜S2 研究デザイン・患者背景","url":"pages/articles-gl-albumin-sepsis2025.html#design","desc":"IPTW後の患者特性・選択基準（eGFR<60・SCr高値・vasopressors）","keywords":"アルブミン 敗血症性ショック 腎障害 eGFR 60 SCr 1.1 1.2 APACHE II IPTW PINC AI 除外基準 ESRD"},
  {"title":"アルブミン研究 S3 主要アウトカム（RRTまたは院内死亡）","url":"pages/articles-gl-albumin-sepsis2025.html#primary-outcome","desc":"非アルブミン群33.8% vs アルブミン群39.7%（OR 1.29、P<.001）","keywords":"RRT 腎代替療法 院内死亡 mortality 複合アウトカム OR 1.29 敗血症性ショック アルブミン"},
  {"title":"アルブミン研究 S5 サブグループ：5% vs 25%アルブミン","url":"pages/articles-gl-albumin-sepsis2025.html#subgroup","desc":"5%（OR 1.07、非有意）vs 25%（OR 1.43）— 高張性アルブミンで有意に増悪","keywords":"5%アルブミン 25%アルブミン 高張性 hyperoncotic 等張性 iso-oncotic サブグループ 交互作用 IMV なし 肺水腫 腎疾患 BMI"},
  {"title":"論文まとめ：消化器 / 肝胆道系","url":"pages/articles-guidelines.html#art-gi","desc":"消化器・肝胆道系の注目論文・ガイドライン","keywords":"消化器 肝臓 胆道 膵炎"},
  {"title":"ツムラ医療用漢方製剤一覧（薬価基準収載）128品目リファレンス","url":"pages/articles-gl-tsumura-kampo.html","desc":"ツムラ医療用漢方製剤 TJ-1〜TJ-138 の効能・用量の完全リファレンス","keywords":"漢方 kampo 漢方薬 ツムラ tsumura 大建中湯 daikenchuto TJ-100 芍薬甘草湯 TJ-68 六君子湯 TJ-43 補中益気湯 TJ-41 五苓散 TJ-17 半夏瀉心湯 TJ-14 抑肝散 TJ-54 小建中湯 TJ-99 牛車腎気丸 TJ-107 小青竜湯 TJ-19 人参湯 TJ-32 真武湯 TJ-30 葛根湯 TJ-1 麻黄湯 TJ-27 防風通聖散 TJ-62 八味地黄丸 TJ-7 十全大補湯 TJ-48 当帰芍薬散 TJ-23 加味逍遙散 TJ-24 桂枝茯苓丸 TJ-25 間質性肺炎 用量 7.5g 9.0g 15.0g 18.0g 便秘 めまい 不眠 浮腫 下痢 嘔吐 腹部膨満 筋痙攣 冷え症 更年期障害"},
  {"title":"ツムラ漢方 — 用法及び用量（標準 7.5g・特別用量一覧）","url":"pages/articles-gl-tsumura-kampo.html#kampo-dosage","desc":"標準用量7.5g/日（115品目）と特別用量設定製剤（TJ-97・98・99・100等9品目）の一覧","keywords":"用量 用法 7.5g 9.0g 10.5g 15.0g 18.0g 大建中湯 小建中湯 大防風湯 黄耆建中湯 分包 食前 食間"},
  {"title":"ツムラ漢方 — 警告・禁忌（間質性肺炎）","url":"pages/articles-gl-tsumura-kampo.html#kampo-warning","desc":"全漢方製剤共通の間質性肺炎警告 — 発熱・咳嗽・呼吸困難・胸部X線異常でただちに中止","keywords":"間質性肺炎 interstitial pneumonia 警告 禁忌 小柴胡湯 TJ-9 発熱 咳嗽 呼吸困難 副作用 漢方 重篤"},
  {"title":"ツムラ漢方 — 全製剤リファレンス一覧（TJ-1〜TJ-138）","url":"pages/articles-gl-tsumura-kampo.html#kampo-list","desc":"128品目全製剤の漢方名・効能・用量を搭載した検索可能リファレンステーブル","keywords":"漢方 全製剤 一覧 TJ番号 効能 用量 検索 リファレンス 大建中湯 芍薬甘草湯 補中益気湯"},
  {"title":"論文まとめ：血液系","url":"pages/articles-guidelines.html#art-heme","desc":"血液系の注目論文・ガイドライン","keywords":"血液 輸血 DIC 凝固"},
  {"title":"血小板減少症の鑑別フロー（Intensivist 2026）","url":"pages/articles-gl-thrombocytopenia2026.html","desc":"ICUにおける血小板減少症の循環構造型鑑別フロー（梅村 穣）","keywords":"血小板減少 血小板減少症 鑑別 DIC TMA TTP HUS HIT ECMO 偽性血小板減少 EDTA 循環型フロー 梅村 Intensivist 血球貪食 HPS SFTS ヘパリン 溶血 破砕赤血球 ADAMTS13 von Willebrand"},
  {"title":"聖路加ICU 輸血ガイド（ESICM 2020 / ACCP 2025 / AABB 2025）","url":"pages/articles-gl-transfusion2026.html","desc":"ICUにおけるRBC・血小板輸血トリガーの患者カテゴリ別まとめ","keywords":"輸血 transfusion 赤血球 RBC 血小板 PLT 制限的輸血 restrictive liberal ACS 急性冠症候群 脳障害 外傷性脳損傷 TBI SAH TRAIN study REALITY trial ESICM ACCP AABB Hb 7 Hb 9 輸血トリガー 敗血症 心臓外科 消化管出血 Prolonged Weaning ITP TTP HIT 輸血不応 HLA CCI PACER PATCH 血小板製剤使用ガイドライン"},
  {"title":"聖路加ICU 輸血ガイド — 第1章 RBC輸血","url":"pages/articles-gl-transfusion2026.html#rbc","desc":"赤血球輸血トリガーの患者カテゴリ別推奨","keywords":"赤血球輸血 RBC 制限的 restrictive liberal Hb 7 Hb 9 Hb 10 一般ICU 消化管出血 ACS 心臓外科 敗血症 Prolonged Weaning 脳障害 ESICM ACCP"},
  {"title":"RBC輸血 S1 一般ICU患者（Hb <7）","url":"pages/articles-gl-transfusion2026.html#rbc-general","desc":"輸血ガイド 第1章 › S1","keywords":"一般ICU 非出血 Hb 7 制限的 restrictive strategy 強い推奨 ESICM ACCP 組織低酸素 乳酸 ScvO2"},
  {"title":"RBC輸血 S2 急性消化管出血（Hb 7〜8）","url":"pages/articles-gl-transfusion2026.html#rbc-gi","desc":"輸血ガイド 第1章 › S2","keywords":"消化管出血 GI bleeding Hb 8 制限的 REALITY trial JAMA 2021 936例"},
  {"title":"RBC輸血 S3 ACS（Liberal Hb 9〜10）","url":"pages/articles-gl-transfusion2026.html#rbc-acs","desc":"輸血ガイド 第1章 › S3","keywords":"ACS 急性冠症候群 Liberal Hb 9 Hb 10 心筋虚血 冠症候群 ESICM ACCP 条件付き 慢性冠症候群 対象外"},
  {"title":"RBC輸血 S8 脳障害患者（院内独自 Hb <9）","url":"pages/articles-gl-transfusion2026.html#rbc-brain","desc":"輸血ガイド 第1章 › S8","keywords":"脳障害 TBI 外傷性脳損傷 SAH くも膜下出血 脳卒中 Hb 9 TRAIN study JAMA 2024 院内独自推奨 GOSE"},
  {"title":"聖路加ICU 輸血ガイド — 第2章 血小板輸血","url":"pages/articles-gl-transfusion2026.html#plt","desc":"血小板輸血トリガーの病態別推奨","keywords":"血小板輸血 PLT 予防的輸血 ITP TTP HIT 輸血不応 HLA CCI PACER 化学療法 造血幹細胞移植 腰椎穿刺 CVカテーテル 活動性出血"},
  {"title":"血小板輸血 CQ3 処置・手術前（PACER試験）","url":"pages/articles-gl-transfusion2026.html#plt-cq3","desc":"輸血ガイド 第2章 › CQ3","keywords":"CVカテーテル 処置前 手術前 2万 1万 5万 圧迫止血 圧迫不可 圧迫可能 内頸静脈 大腿静脈 鎖骨下 腰椎穿刺 PACER NEJM 2023 脊髄血腫"},
  {"title":"血小板輸血 CQ4 ITP（予防的輸血なし）","url":"pages/articles-gl-transfusion2026.html#plt-cq4","desc":"輸血ガイド 第2章 › CQ4","keywords":"ITP 特発性血小板減少性紫斑病 予防的輸血なし IVIG ステロイド TPO-RA 活動性出血"},
  {"title":"血小板輸血 CQ5 TTP（避けるべき）","url":"pages/articles-gl-transfusion2026.html#plt-cq5","desc":"輸血ガイド 第2章 › CQ5","keywords":"TTP 血栓性血小板減少性紫斑病 予防的輸血禁忌 血漿交換 ADAMTS13 FFP 血栓促進"},
  {"title":"血小板輸血 CQ6 HIT（避けるべき）","url":"pages/articles-gl-transfusion2026.html#plt-cq6","desc":"輸血ガイド 第2章 › CQ6","keywords":"HIT ヘパリン起因性血小板減少症 予防的輸血禁忌 アルガトロバン 代替抗凝固 動脈血栓"},
  {"title":"血小板輸血 CQ8 活動性出血時の目標血小板数","url":"pages/articles-gl-transfusion2026.html#plt-cq8","desc":"輸血ガイド 第2章 › CQ8","keywords":"活動性出血 5万 10万 外傷性頭蓋内出血 脳出血 抗血小板薬 アスピリン クロピドグレル PATCH試験 高血圧性脳出血"},
  {"title":"ICU血小板減少症 DIC vs TMA 鑑別アルゴリズム（Vincent 2018）","url":"pages/articles-gl-dic-tma2018.html","desc":"DIC・TTP・HUSを迅速鑑別するアルゴリズム — 凝固検査・ADAMTS13・STEC検査の活用法（Critical Care 2018）","keywords":"DIC 播種性血管内凝固 TMA 血栓性微小血管障害 TTP 血栓性血小板減少性紫斑病 HUS 溶血性尿毒症症候群 aHUS 非典型HUS ADAMTS13 血漿交換 PLASMIC スコア エクリズマブ STEC 志賀毒素 スキストサイト 破砕赤血球 MAHA 微小血管障害性溶血性貧血 LDH 凝固機能 フィブリノゲン Dダイマー Vincent Critical Care 2018 鑑別 血小板減少 ICU"},
  {"title":"ICU血小板減少症 DIC vs TMA — S1 背景・疫学","url":"pages/articles-gl-dic-tma2018.html#s1-background","desc":"ICUにおける血小板減少症の頻度（25〜55%）とDIC・TTPの疫学","keywords":"血小板減少 ICU DIC 25% 55% 9% 19% TTP 疫学 MAHA"},
  {"title":"ICU血小板減少症 DIC vs TMA — S2 凝固機能検査","url":"pages/articles-gl-dic-tma2018.html#s2-differentiation","desc":"DIC vs TMAの最重要鑑別点：凝固機能検査（PT・aPTT・フィブリノゲン・Dダイマー）","keywords":"凝固機能 PT aPTT フィブリノゲン Dダイマー アンチトロンビン 鑑別 DIC TMA 凝固異常"},
  {"title":"ICU血小板減少症 DIC vs TMA — S3 診断アルゴリズム","url":"pages/articles-gl-dic-tma2018.html#s3-algorithm","desc":"Step1：DIC vs TMA、Step2：ADAMTS13でTTP診断、Step3：STEC検査でHUS鑑別","keywords":"アルゴリズム ADAMTS13 TTP 血漿交換 STEC-HUS aHUS 診断フロー"},
  {"title":"ICU血小板減少症 DIC vs TMA — S5 PLASMICスコア","url":"pages/articles-gl-dic-tma2018.html#s5-plasmic","desc":"ADAMTS13が測定できない場合のTTP予測ツール：PLASMICスコア（7成分）","keywords":"PLASMIC スコア ADAMTS13 TTP 予測 代替 血小板 LDH INR クレアチニン"},
  {"title":"論文まとめ：感染症","url":"pages/articles-guidelines.html#art-id","desc":"感染症の注目論文・ガイドライン","keywords":"感染症 抗菌薬 敗血症 セプシス"},
  {"title":"移植における免疫抑制薬と感染リスク — 免疫抑制のネットステート（CID 2021）","url":"pages/articles-gl-immunosuppression-transplant2021.html","desc":"SOT（固形臓器移植）における免疫抑制のネットステートの概念・評価ツール・各薬剤の免疫影響・感染時の免疫抑制調整戦略のレビュー（Roberts & Fishman, CID 2021）","keywords":"免疫抑制 net state of immunosuppression ネットステート 固形臓器移植 SOT solid organ transplantation 免疫機能アッセイ 薬物血中濃度 TTV torque teno virus BKPyV BKポリオーマウイルス CMV サイトメガロウイルス EBV PTLD 移植後リンパ増殖性疾患 カルシニューリン阻害薬 CNI タクロリムス シクロスポリン MMF ミコフェノール酸モフェチル アザチオプリン mTOR mTOR阻害薬 シロリムス グルココルチコイド ステロイド ATG Belatacept Alemtuzumab Rituximab Eculizumab トシリズマブ IL-6 日和見感染 opportunistic infection グラフト拒絶 IRIS 免疫再構成症候群 侵襲性真菌感染 Aspergillus Pneumocystis PJP Nocardia 結核 TB 敗血症 COVID-19 Norovirus 低ガンマグロブリン血症 腸内細菌叢 dysbiosis Roberts Fishman MGH ハーバード"},
  {"title":"免疫抑制のネットステート — 概念と感染時の4つの考慮点","url":"pages/articles-gl-immunosuppression-transplant2021.html#concept","desc":"感染リスクに寄与する全因子の概念フレームワーク。感染時の免疫抑制調整に必要な4つの評価軸","keywords":"ネットステート 免疫抑制 グラフト拒絶 IRIS 免疫再構成症候群 感染管理 SOT 固形臓器移植"},
  {"title":"免疫機能評価ツール — TTV・IRP・sCD30・iATP・IFN-γ","url":"pages/articles-gl-immunosuppression-transplant2021.html#immune-assessment","desc":"CMV/EBV/BK定量的ウイルス量、Torque teno virus（TTV）、複合免疫プロファイル（IRP）、sCD30、iATPなど各アッセイの臨床的意義","keywords":"TTV torque teno virus 免疫機能アッセイ sCD30 iATP IFN-γ IRP 複合免疫プロファイル CD4 CD8 リンパ球 低ガンマグロブリン血症 補体 MBL 腸内細菌叢"},
  {"title":"各免疫抑制薬の免疫影響 — CNI・MMF・ステロイド・Alemtuzumab・Eculizumab","url":"pages/articles-gl-immunosuppression-transplant2021.html#drug-effects","desc":"CNI・MMF・アザチオプリン・mTOR阻害薬・グルココルチコイド・ATG・Belatacept・Alemtuzumab・Rituximab・Eculizumab・IL-6拮抗薬の自然免疫・細胞性免疫・液性免疫への影響","keywords":"CNI タクロリムス シクロスポリン MMF ミコフェノール酸 アザチオプリン mTOR シロリムス ステロイド プレドニゾン ATG Belatacept Alemtuzumab Campath Rituximab Eculizumab IL-6 トシリズマブ 自然免疫 細胞性免疫 液性免疫 NK細胞 樹状細胞 IMPDH カルシニューリン"},
  {"title":"感染症別の免疫抑制調整 — CMV・PTLD・BKV・敗血症・真菌","url":"pages/articles-gl-immunosuppression-transplant2021.html#infection-management","desc":"CMV・EBV/PTLD・侵襲性真菌感染・結核・重症敗血症・BKポリオーマウイルス・Norovirusにおける免疫抑制削減の実際（Table 4の臨床研究含む）","keywords":"CMV サイトメガロウイルス PTLD EBV 侵襲性真菌 Aspergillus PJP Pneumocystis クリプトコッカス 結核 TB 敗血症 BKPyV BKウイルス BK nephropathy Norovirus COVID-19 免疫抑制削減 グラフト拒絶 CNI MMF 段階的削減 IRIS"},
  {"title":"院内細菌性髄膜炎 — 疫学・診断・抗菌薬治療（NEJM 2010）","url":"pages/articles-gl-nosocomial-meningitis2010.html","desc":"van de Beek et al. NEJM 2010 — 術後・カテーテル・外傷後髄膜炎の病態・診断・経験的抗菌薬・脳室内投与・カテーテル管理","keywords":"院内髄膜炎 nosocomial meningitis 脳室炎 ventriculitis EVD 外部脳室ドレナージ CSFシャント 開頭術 craniotomy 頭蓋底骨折 basilar skull fracture 腰椎穿刺 脳室内抗菌薬 intraventricular antibiotic バンコマイシン vancomycin メロペネム meropenem セフェピム cefepime セフタジジム ceftazidime アシネトバクター Acinetobacter コリスチン colistin ポリミキシン polymyxin MDR 多剤耐性 グラム陰性桿菌 Propionibacterium acnes コアグラーゼ陰性ブドウ球菌 S. epidermidis CSF培養 乳酸値 NEJM 2010 van de Beek Tunkel Drake 水頭症 hydrocephalus 脳室内出血 無菌性髄膜炎 aseptic meningitis"},
  {"title":"院内髄膜炎 — 疫学（開頭術・シャント・EVD・頭部外傷・腰椎穿刺）","url":"pages/articles-gl-nosocomial-meningitis2010.html#nm-s1","desc":"発生率：開頭術0.8–1.5% / 内部シャント4–17% / EVD8% / 頭蓋底骨折最大25%（中央値11日）/ LP 1/50,000","keywords":"開頭術後髄膜炎 0.8 1.5 内部脳室カテーテル シャント 4 17 外部脳室カテーテル EVD 8 外部腰椎カテーテル 頭蓋底骨折 25 腰椎穿刺 50000 頭部外傷 二重手袋"},
  {"title":"院内髄膜炎 — 診断（CSF培養・乳酸値・無菌性髄膜炎）","url":"pages/articles-gl-nosocomial-meningitis2010.html#nm-s4","desc":"CSF培養（好気性・嫌気性）が基本。乳酸≥4 mmol/L：感度88%・特異度98%（神経外科術後）。術後無菌性髄膜炎は最大70%。","keywords":"CSF培養 CSF乳酸 lactate 4 mmol 感度 88 特異度 98 PPV 96 NPV 94 無菌性髄膜炎 aseptic 70% グラム染色 白血球数 PCR 乳酸値 神経外科術後"},
  {"title":"院内髄膜炎 — 経験的抗菌薬（病態別レジメン）","url":"pages/articles-gl-nosocomial-meningitis2010.html#nm-s5","desc":"術後/カテーテル/外傷：バンコマイシン+セフェピム/セフタジジム/メロペネム。頭蓋底骨折：バンコマイシン+セフトリアキソン。","keywords":"経験的抗菌薬 empirical バンコマイシン vancomycin セフェピム cefepime セフタジジム ceftazidime メロペネム meropenem セフトリアキソン ceftriaxone 15 20 トラフ trough 72時間 術後 カテーテル 頭蓋底骨折"},
  {"title":"院内髄膜炎 — 脳室内抗菌薬投与（用量・モニタリング）","url":"pages/articles-gl-nosocomial-meningitis2010.html#nm-s6","desc":"バンコマイシン5–20 mg/日、ゲンタマイシン4–8 mg（成人）、コリスチン10 mg/日。トラフ÷MIC >10–20を目標。","keywords":"脳室内投与 intraventricular intrathecal バンコマイシン 5 20 mg ゲンタマイシン gentamicin アミカシン amikacin ポリミキシン polymyxin コリスチン colistin トラフ trough MIC 10 20 保存剤不含"},
  {"title":"院内髄膜炎 — MDRアシネトバクター・カテーテル抜去","url":"pages/articles-gl-nosocomial-meningitis2010.html#nm-s7","desc":"MDR Acinetobacter：メロペネム±脳室内アミノグリコシド→カルバペネム耐性にはコリスチン/ポリミキシンB。シャント抜去+外部置換 >85%成功。","keywords":"アシネトバクター Acinetobacter MDR 多剤耐性 コリスチン colistin ポリミキシン polymyxin カルバペネム耐性 シャント抜去 外部ドレナージ 成功率 85 65 35 再発 26 再留置"},
  {"title":"緑膿菌菌血症の抗菌薬投与期間 7日 vs 14日（BALANCE post hoc, CID 2026）","url":"pages/articles-gl-pa-bacteremia2026.html","desc":"BALANCE試験のpost hoc解析 — P. aeruginosa菌血症157例で7日間 vs 14日間の投与期間を比較","keywords":"緑膿菌 Pseudomonas aeruginosa 菌血症 bacteremia 抗菌薬 投与期間 duration BALANCE trial 7日間 14日間 90日死亡率 post hoc RCT ピペラシリン タゾバクタム セフタジジム メロペネム シプロフロキサシン MDR DTR SHORTEN-2 Yahav CID Clinical Infectious Diseases 2026 院内感染 耐性 バイオフィルム qSOFA 年齢 抗菌薬フリー days alive antibiotic-free"},
  {"title":"ペラミビル（Alpivab）：単純性インフルエンザ治療のレビュー（Drugs 2018）","url":"pages/articles-gl-peramivir-review.html","desc":"静注ペラミビルの薬理・臨床試験・用量・耐性・臨床的位置づけのまとめ","keywords":"ペラミビル peramivir Alpivab Rapivab インフルエンザ influenza ノイラミニダーゼ阻害薬 NAI 静注 単回投与 オセルタミビル ザナミビル H275Y 耐性 腎機能 腎障害 小児 悪心 嘔吐 嚥下困難 Drugs 2018"},
  {"title":"論文まとめ：栄養 / 代謝系","url":"pages/articles-guidelines.html#art-nutrition","desc":"栄養・代謝系の注目論文・ガイドライン","keywords":"栄養 代謝 経腸栄養 血糖"},

  // ── Enteral Nutrition in Hospitalized Adults（NEJM 2025）──
  {"title":"Enteral Nutrition in Hospitalized Adults（NEJM 2025）","url":"pages/articles-gl-en-nejm2025.html","desc":"入院患者における経腸栄養のレビュー — 栄養不良の疫学・病態・ICU/内科/外科別エビデンス・実践的管理（Gramlich & Guenter, NEJM 2025）","keywords":"経腸栄養 enteral nutrition EN 入院患者 hospitalized 栄養不良 disease-related malnutrition EFFORT NUTRIREA-2 NUTRIREA-3 CALORIES EFFORT Protein OPENS 間接熱量測定 indirect calorimetry 容量ベース投与 volume-based feeding 幽門後投与 postpyloric feeding 胃残量 GRV gastric residual volume リフィーディング症候群 refeeding syndrome チアミン thiamine ENFit 経腸アクセス enteral access 経鼻胃管 NG tube PEG PEG-J 経皮的胃瘻 GLIM AAIM 栄養スクリーニング malnutrition screening ASPEN ESPEN SCCM Gramlich Guenter NEJM 2025 NEJMra2406954 N Engl J Med 392 1518"},
  {"title":"EN — 第1章 入院患者の栄養ケア（NEJM 2025）","url":"pages/articles-gl-en-nejm2025.html#en-ch1","desc":"疾患関連栄養不良の疫学・栄養ケアパスウェイ・EFFORT試験・医療的栄養療法のエビデンス","keywords":"栄養不良 30 45% 入院患者 EFFORT OR 0.79 0.65 CRP 100 inflammatory marker 6803 メタ解析 栄養スクリーニング Malnutrition Screening Tool NRS-2002 GLIM AAIM 75% 5日間"},
  {"title":"EN — 第2章 適応と病態生理（NEJM 2025）","url":"pages/articles-gl-en-nejm2025.html#en-ch2","desc":"経腸栄養の適応疾患・禁忌・急性期の代謝変化・筋萎縮・underfeeding戦略の根拠","keywords":"腸閉塞 イレウス ショック 腸管虚血 禁忌 contraindication 嚥下障害 dysphagia 代謝 筋萎縮 muscle wasting ubiquitin proteasome 過小投与 underfeeding 70% ケトン産生 ketogenesis 高血糖 hyperglycemia 過剰栄養 overfeeding 尿素産生 ureagenesis 高TG 回復期 recovery"},
  {"title":"EN — 第3章 特定患者集団（NEJM 2025）","url":"pages/articles-gl-en-nejm2025.html#en-ch3","desc":"ガイドライン別推奨（Table 1）・ICU主要RCT（NUTRIREA-3 / EFFORT Protein）・内科外科患者のエビデンス","keywords":"ESPEN ASPEN SCCM ガイドライン 20-25 kcal/kg 12-25 kcal/kg 1.3 g/kg 1.2-2.0 g/kg NUTRIREA-3 3044例 high-dose high dose 25kcal 6kcal 有害 EFFORT Protein 1301例 2.2g/kg 1.2g/kg AKI 腎障害 OPENS 脳卒中 stroke 321例 34% 17% OR 2.89 食道切除術 早期開始 48時間 術後 postoperative"},
  {"title":"EN — 第4章 実践的考慮事項（NEJM 2025）","url":"pages/articles-gl-en-nejm2025.html#en-ch4","desc":"経腸アクセスの選択・GRV廃止・リフィーディング症候群対策・容量ベース投与・ENFit","keywords":"経鼻胃管 nasogastric NG 経鼻空腸管 NJ nasojejunal PEG PEG-J PEJ 内視鏡的留置 endoscopic 幽門後投与 postpyloric 3248例 誤嚥 aspiration 肺炎 pneumonia 胃残量 GRV 500ml ENFit 誤接続 リフィーディング refeeding チアミン thiamine 100mg K P Mg 500kcal 容量ベース投与 volume-based feeding 速度固定 rate-based"},

  // ── ASPEN 2021 重症患者栄養サポートガイドライン ──
  {"title":"ASPEN 2021 重症患者栄養サポートガイドライン（JPEN 2022）","url":"pages/articles-gl-aspen-nutrition2021.html","desc":"重症成人ICU患者に対するエネルギー・タンパク質・EN vs PN・SPN・ILE選択の5つのPICO推奨（GRADE）","keywords":"ASPEN 栄養 nutrition サポート 重症 ICU エネルギー energy カロリー protein タンパク質 経腸栄養 EN enteral 経静脈栄養 PN parenteral 補足的PN SPN supplemental 脂肪乳剤 ILE lipid injectable emulsion 大豆油 soybean oil 魚油 fish oil FO 混合油脂 MCT オリーブ油 olive oil GRADE 過剰栄養 overfeeding 低栄養 underfeeding Compher Bingham JPEN 2022 12-25kcal 1.2-2.0g/kg Harvey NUTRIREA-2 Reignier EPaNIC Casaer"},
  {"title":"ASPEN 2021 — 推奨1：エネルギー投与量","url":"pages/articles-gl-aspen-nutrition2021.html#aspen-q1","desc":"ICU第1〜10日に12〜25 kcal/kg/日を提案（Weak推奨・Moderate evidence）／13試験8,690例","keywords":"エネルギー投与量 kcal/kg 高エネルギー 低エネルギー 過剰栄養 安全性解析 ICU 死亡率 菌血症 肺炎 LOS"},
  {"title":"ASPEN 2021 — 推奨2：タンパク質投与量","url":"pages/articles-gl-aspen-nutrition2021.html#aspen-q2","desc":"1.2〜2.0 g/kg/日を個別化（Weak推奨・Low evidence）／4試験697例","keywords":"タンパク質 protein g/kg 高タンパク アミノ酸 ICU 栄養 IVAA"},
  {"title":"ASPEN 2021 — 推奨3：EN vs PN（第1週）","url":"pages/articles-gl-aspen-nutrition2021.html#aspen-q3","desc":"どちらでも可（Strong推奨・High evidence）／Harvey 2014・NUTRIREA-2 計4,798例","keywords":"経腸栄養 EN 経静脈栄養 PN 第1週 Harvey NUTRIREA-2 Reignier ルート選択 感染 死亡率"},
  {"title":"ASPEN 2021 — 推奨4：SPN（第1週は開始しない）","url":"pages/articles-gl-aspen-nutrition2021.html#aspen-q4","desc":"ICU入室7日目より前にSPN不開始（Strong推奨・High evidence）／6試験6,731例","keywords":"SPN 補足的PN supplemental parenteral nutrition EPaNIC Casaer 7日 early 第1週"},
  {"title":"ASPEN 2021 — 推奨5：脂肪乳剤（ILE）の選択","url":"pages/articles-gl-aspen-nutrition2021.html#aspen-q5","desc":"混合油脂・魚油含有ILE vs 大豆油ILE（いずれでも可、Weak推奨・Low evidence）","keywords":"ILE 脂肪乳剤 大豆油 soybean oil 混合油脂 mixed oil 魚油 fish oil FO omega-3 MCT オリーブ olive 肺炎 トリグリセリド"},

  {"title":"代謝性アシドーシス 最新エビデンス（ICM 2025）","url":"pages/articles-gl-metabolic-acidosis2025.html","desc":"ICUにおける代謝性アシドーシスの疫学・臓器影響・診断（HAGMA/NAGMA）・重炭酸ナトリウム療法・KRTの最新エビデンスまとめ","keywords":"代謝性アシドーシス metabolic acidosis HAGMA NAGMA アニオンギャップ anion gap 乳酸アシドーシス lactic acidosis 重炭酸ナトリウム sodium bicarbonate BICAR-ICU AKI 腎代替療法 KRT RRT Stewart法 SID 呼吸代償 Winters式 pH アシデミア acidemia DKA ケトアシドーシス 腫瘍崩壊 TLS 低カリウム 低カルシウム Jung Forni Jaber Intensive Care Med 2025"},

  // ── 混合性酸塩基平衡障害 Core Curriculum 2025 ──
  {"title":"混合性酸塩基平衡障害 Core Curriculum 2025（Am J Kidney Dis）","url":"pages/articles-gl-mixed-acidbase2025.html","desc":"混合性酸塩基平衡障害の系統的診断アプローチ：代償公式・アニオンギャップ・6ステップ評価と8症例解説","keywords":"酸塩基平衡 acid-base 混合性障害 mixed disorder アニオンギャップ anion gap 代償公式 Winter式 D-乳酸 D-lactic acidosis アルコール性ケトアシドーシス AKA サリチル酸中毒 COPD 呼吸性アシドーシス 代謝性アルカローシス RTA 1型 2型 4型 尿細管性アシドーシス AG Henderson-Hasselbalch Palmer AJKD 2025"},
  {"title":"第1章 混合性酸塩基障害の診断アプローチ","url":"pages/articles-gl-mixed-acidbase2025.html#mab-ch1","desc":"混合性酸塩基平衡障害 › 第1章","keywords":"混合性酸塩基 診断アプローチ Henderson-Hasselbalch 代償 アニオンギャップ ΔAG ΔHCO3 尿浸透圧ギャップ 尿アニオンギャップ Cl Na 系統的評価"},
  {"title":"代償公式（Box 1）と混合性障害の診断","url":"pages/articles-gl-mixed-acidbase2025.html#mab1-s2","desc":"混合性酸塩基平衡障害 第1章 › SECTION 2","keywords":"代償公式 暗記 急性呼吸性アシドーシス 慢性呼吸性アシドーシス 急性呼吸性アルカローシス 慢性呼吸性アルカローシス 代謝性アシドーシス Winter式 代謝性アルカローシス 0.7 3.5 1mEq 2mEq 5mEq"},
  {"title":"アニオンギャップ・ΔAG/ΔHCO3・電解質評価","url":"pages/articles-gl-mixed-acidbase2025.html#mab1-s3","desc":"混合性酸塩基平衡障害 第1章 › SECTION 3","keywords":"アニオンギャップ AG アルブミン補正 ΔAG ΔHCO3 代謝性アルカローシス 正常AG 細胞内緩衝 Cl Na 電解質 尿浸透圧ギャップ 尿アニオンギャップ NH4 アンモニウム"},
  {"title":"系統的アプローチ 6ステップ（Box 2）","url":"pages/articles-gl-mixed-acidbase2025.html#mab1-s4","desc":"混合性酸塩基平衡障害 第1章 › SECTION 4","keywords":"6ステップ 系統的 Na Cl アニオンギャップ ΔAG 血液ガス K カリウム RTA 鑑別"},
  {"title":"Case 1：正常AG代謝性アシドーシス + 呼吸性アシドーシス（1型RTA）","url":"pages/articles-gl-mixed-acidbase2025.html#mab2-s1","desc":"混合性酸塩基平衡障害 第2章 › Case 1","keywords":"正常AG 代謝性アシドーシス 呼吸性アシドーシス 1型RTA 遠位型 尿細管性アシドーシス 低カリウム K補充 HCO3補正 Winter式 呼吸筋麻痺 横紋筋融解"},
  {"title":"Case 2：呼吸性アルカローシス + AG増加型代謝性アシドーシス（サリチル酸）","url":"pages/articles-gl-mixed-acidbase2025.html#mab2-s2","desc":"混合性酸塩基平衡障害 第2章 › Case 2","keywords":"サリチル酸 salicylate 中毒 呼吸性アルカローシス AG増加 ケトン体 乳酸 敗血症 肝疾患 過換気 意識障害"},
  {"title":"Case 3：代謝性アルカローシス + 呼吸性アルカローシス（腎結石・嘔吐）","url":"pages/articles-gl-mixed-acidbase2025.html#mab2-s3","desc":"混合性酸塩基平衡障害 第2章 › Case 3","keywords":"代謝性アルカローシス 呼吸性アルカローシス 腎結石 嘔吐 疼痛 pH 7.61 アルカレミア 酸素解離曲線 生食補液"},
  {"title":"Case 4：慢性呼吸性アシドーシス + 代謝性アルカローシス（COPD + ループ利尿薬）","url":"pages/articles-gl-mixed-acidbase2025.html#mab2-s4","desc":"混合性酸塩基平衡障害 第2章 › Case 4","keywords":"COPD 慢性呼吸性アシドーシス ループ利尿薬 代謝性アルカローシス HCO3 Cl 腎代償 post-hypercapnic アセタゾラミド"},
  {"title":"Post-hypercapnic代謝性アルカローシスとCOPD管理","url":"pages/articles-gl-mixed-acidbase2025.html#mab3-s1","desc":"混合性酸塩基平衡障害 第3章 › SECTION 1","keywords":"post-hypercapnic 代謝性アルカローシス COPD 挿管 人工呼吸 PaCO2 急速低下 アセタゾラミド 生食 EABV 有効動脈血液量"},
  {"title":"Case 5：慢性呼吸性アシドーシス + 急性呼吸性アシドーシス（CO₂ナルコーシス）","url":"pages/articles-gl-mixed-acidbase2025.html#mab3-s2","desc":"混合性酸塩基平衡障害 第3章 › Case 5","keywords":"CO2ナルコーシス COPD 肺炎 ゲンタマイシン 神経筋遮断 高流量酸素 Haldane効果 死腔 低酸素性換気駆動 SaO2 88 92"},
  {"title":"Case 6：AG増加型 + 正常AG代謝性アシドーシス（D-乳酸アシドーシス）","url":"pages/articles-gl-mixed-acidbase2025.html#mab4-s1","desc":"混合性酸塩基平衡障害 第4章 › Case 6","keywords":"D-乳酸 D-lactic acid アシドーシス 短腸症候群 short bowel 腸管切除 食後 失調 構音障害 L-乳酸 測定不能 腸内細菌 炭水化物 腎尿細管 立体選択性"},
  {"title":"Case 7：AG増加型代謝性アシドーシス + 代謝性アルカローシス（AKA）","url":"pages/articles-gl-mixed-acidbase2025.html#mab4-s2","desc":"混合性酸塩基平衡障害 第4章 › Case 7","keywords":"アルコール性ケトアシドーシス AKA alcoholic ketoacidosis 嘔吐 代謝性アルカローシス 正常pH AG増加 ΔAG ΔHCO3 アルコール離脱 トリプル酸塩基"},
  {"title":"Case 8：トリプル酸塩基障害（下痢 + 嘔吐）","url":"pages/articles-gl-mixed-acidbase2025.html#mab4-s3","desc":"混合性酸塩基平衡障害 第4章 › Case 8","keywords":"トリプル酸塩基障害 triple acid-base 下痢 嘔吐 正常AG 代謝性アルカローシス 呼吸性アルカローシス 相殺 pH正常 低カリウム 脱水"},

  {"title":"論文まとめ：筋骨格系","url":"pages/articles-guidelines.html#art-msk","desc":"筋骨格系の注目論文・ガイドライン","keywords":"筋骨格 リハビリ ICU-AW"},
  {"title":"論文まとめ：予防","url":"pages/articles-guidelines.html#art-ppx","desc":"予防の注目論文・ガイドライン","keywords":"予防 DVT VAP 褥瘡 潰瘍"},

  // ── ICUカンファレンス By System ──
  {"title":"プレゼンテーションの総論","url":"pages/schedule-icu-conf.html#conf-section1","desc":"ICUカンファレンス","keywords":"SECTION 1 総論 OAP カンファレンス 目的 Plan チーム"},
  {"title":"STEP 1 Objective Dataを集められる","url":"pages/schedule-icu-conf.html#conf-section1","desc":"ICUカンファレンス › 総論","keywords":"Objective Data 客観的 データ収集 ステップ1"},
  {"title":"STEP 2 Assessmentできる","url":"pages/schedule-icu-conf.html#conf-section1","desc":"ICUカンファレンス › 総論","keywords":"Assessment 評価 アセスメント ステップ2"},
  {"title":"STEP 3 Planを提示できる","url":"pages/schedule-icu-conf.html#conf-section1","desc":"ICUカンファレンス › 総論","keywords":"Plan プラン 提案 到達目標 ステップ3"},
  {"title":"By System vs By Problem","url":"pages/schedule-icu-conf.html#conf-section2","desc":"ICUカンファレンス","keywords":"SECTION 2 By System By Problem 長所 短所 比較"},
  {"title":"Opening Statement","url":"pages/schedule-icu-conf.html#conf-section3","desc":"ICUカンファレンス › プレゼンの流れ","keywords":"Part 1 オープニング 全体像 大方針"},
  {"title":"Closing：To Doの確認","url":"pages/schedule-icu-conf.html#conf-section3","desc":"ICUカンファレンス › プレゼンの流れ","keywords":"Part 3 ToDo リマインド まとめ"},
  {"title":"#1 Neurological System 神経系","url":"pages/schedule-icu-conf.html#sys-neuro","desc":"ICUカンファレンス › By System","keywords":"神経 意識レベル 鎮静 鎮痛 せん妄 GCS RASS BPS CAM-ICU 脳外科 不眠 ミダゾラム プロポフォール デクスメデトミジン フェンタニル レミフェンタニル"},
  {"title":"#2 Cardiological System 循環器系","url":"pages/schedule-icu-conf.html#sys-cardio","desc":"ICUカンファレンス › By System","keywords":"循環 昇圧薬 降圧薬 体液量 ショック ノルアドレナリン ピトレシリン ニカルジピン 組織還流 乳酸値 CRT 輸液"},
  {"title":"#3 Respiratory System 呼吸器系","url":"pages/schedule-icu-conf.html#sys-resp","desc":"ICUカンファレンス › By System","keywords":"呼吸 挿管 非挿管 HFNC NIV 人工呼吸器 PCV VCV PSV 肺保護換気 抜管 SAT SBT 気管切開 HACOR ROX"},
  {"title":"#4 Nephrological System 腎電解質系","url":"pages/schedule-icu-conf.html#sys-renal","desc":"ICUカンファレンス › By System","keywords":"腎 電解質 透析 血液ガス 酸塩基 Stewart Boston AG 代謝性アシドーシス 低ナトリウム"},
  {"title":"#5 GI / Hepatobiliary 消化器/肝胆道系","url":"pages/schedule-icu-conf.html#sys-gi","desc":"ICUカンファレンス › By System","keywords":"消化器 肝胆道 腹部所見 肝機能 排便 ドレーン ストーマ CDI AST ALT ビリルビン"},
  {"title":"#6 Hematological System 血液系","url":"pages/schedule-icu-conf.html#sys-heme","desc":"ICUカンファレンス › By System","keywords":"血液 貧血 凝固 血小板 輸血 DIC HIT CBC Dダイマー フィブリノーゲン 化学療法"},
  {"title":"#7 Infectious Disease 感染症","url":"pages/schedule-icu-conf.html#sys-id","desc":"ICUカンファレンス › By System","keywords":"感染症 抗菌薬 培養 感染フォーカス de-escalation WBC CRP PCT 炎症マーカー"},
  {"title":"#8 Nutritional / Metabolic 栄養/代謝系","url":"pages/schedule-icu-conf.html#sys-nutr","desc":"ICUカンファレンス › By System","keywords":"栄養 代謝 経腸栄養 EN PN 血糖管理 インスリン カロリー 蛋白 180mg/dL"},
  {"title":"#9 Musculoskeletal 筋骨格系","url":"pages/schedule-icu-conf.html#sys-msk","desc":"ICUカンファレンス › By System","keywords":"筋骨格 リハビリ ICU-AW 安静度 四肢筋力 嚥下力 咳嗽力 離床 PT"},
  {"title":"#10 Prophylaxis 予防","url":"pages/schedule-icu-conf.html#sys-ppx","desc":"ICUカンファレンス › By System","keywords":"予防 DVT ストレス潰瘍 PPI VAP バンドル せん妄 ABCDEF ヘパリン クレキサン 褥瘡 口腔ケア"},

  // ── ID×ICUカンファレンス ──
  {"title":"ID×ICUカンファレンス","url":"pages/schedule-weekly-id-icu.html","desc":"感染症科 森先生による週1レクチャー","keywords":"感染症 森先生 毎週水曜 13:30 ID"},
  {"title":"抗菌薬を学ぶ","url":"pages/schedule-weekly-id-icu.html#id-antibiotics","desc":"ID×ICU › カテゴリ","keywords":"抗菌薬 PK PD アレルギー 耐性GNR 新規抗菌薬 Corynebacterium Prolonged infusion 殺菌性 静菌性"},
  {"title":"真菌感染症","url":"pages/schedule-weekly-id-icu.html#id-fungal","desc":"ID×ICU › カテゴリ","keywords":"Candida 菌血症 Aspergillus ムーコル 真菌"},
  {"title":"免疫不全・予防","url":"pages/schedule-weekly-id-icu.html#id-immunodeficiency","desc":"ID×ICU › カテゴリ","keywords":"免疫不全 CMV Prophylaxis 血液内科 予防抗菌薬 非定型肺炎"},
  {"title":"臓器別感染症","url":"pages/schedule-weekly-id-icu.html#id-organ","desc":"ID×ICU › カテゴリ","keywords":"VAP CRBSI CLABSI 髄膜炎 脳膿瘍 腹腔内感染症 β-ラクタム"},

  // ── 腎臓内科カンファレンス ──
  {"title":"血液透析患者のプレゼンテーション","url":"pages/schedule-renal-conf.html","desc":"腎臓内科カンファレンス 8:15","keywords":"腎臓内科 透析 プレゼン"},
  {"title":"STEP 0 プレゼンの心得","url":"pages/schedule-renal-conf.html#renal-step0","desc":"腎臓内科カンファレンス","keywords":"心得 腎電解質 大方針"},
  {"title":"STEP 1 CKDか？AKIか？","url":"pages/schedule-renal-conf.html#renal-step1","desc":"腎臓内科カンファレンス","keywords":"CKD AKI 患者背景 透析 貧血 MBD DW シャント バスキャス"},
  {"title":"STEP 2 溶質除去が必要か","url":"pages/schedule-renal-conf.html#renal-step2","desc":"腎臓内科カンファレンス","keywords":"溶質除去 AIUE 適応 高K血症 BUN 尿毒症 アシデミア"},
  {"title":"STEP 3 除水が必要か","url":"pages/schedule-renal-conf.html#renal-step3","desc":"腎臓内科カンファレンス","keywords":"除水 限外濾過 ECUM ドライウェイト UFR"},
  {"title":"透析離脱の評価","url":"pages/schedule-renal-conf.html#renal-weaning","desc":"腎臓内科カンファレンス","keywords":"透析離脱 尿量 評価"},
  {"title":"プレゼンテーション例","url":"pages/schedule-renal-conf.html#renal-examples","desc":"腎臓内科カンファレンス","keywords":"プレゼン例 CKDG5D Septic AKI HD 高カリウム"},
  {"title":"Kt/V 透析効率","url":"pages/schedule-renal-conf.html#renal-ktv","desc":"腎臓内科カンファレンス › STEP UP","keywords":"Kt/V 透析効率 透析処方"},

  // ── 動画講座集 カテゴリ ──
  {"title":"聖路加ICU動画講座集","url":"pages/video-lectures.html","desc":"ICUスタッフによる動画講座 全54本","keywords":"動画 講座 ビデオ レクチャー"},
  {"title":"ヒューマンケア・意思決定支援","url":"pages/video-lectures.html#vid-humancare","desc":"動画講座集 › カテゴリ","keywords":"ヒューマンケア 意思決定 ACP チーム医療 石塚 瀬尾 石上"},
  {"title":"呼吸管理","url":"pages/video-lectures.html#vid-respiratory","desc":"動画講座集 › カテゴリ","keywords":"呼吸管理 抜管 肺メカニクス 経肺圧 ARDS NPPV 小児"},
  {"title":"人工呼吸器","url":"pages/video-lectures.html#vid-ventilator","desc":"動画講座集 › カテゴリ","keywords":"人工呼吸器 アラーム 非同調 ASV INTELLiVENT"},
  {"title":"ECMO","url":"pages/video-lectures.html#vid-ecmo","desc":"動画講座集 › カテゴリ","keywords":"ECMO 体外式膜型人工肺 村上"},
  {"title":"鎮静・鎮痛・せん妄","url":"pages/video-lectures.html#vid-sedation","desc":"動画講座集 › カテゴリ","keywords":"鎮静 鎮痛 せん妄 不眠 Sedline 石塚 林 山田"},
  {"title":"神経集中治療","url":"pages/video-lectures.html#vid-neuro","desc":"動画講座集 › カテゴリ","keywords":"神経 脳波 モニタリング 藤本"},
  {"title":"循環・ショック・輸液","url":"pages/video-lectures.html#vid-circulation","desc":"動画講座集 › カテゴリ","keywords":"循環 ショック 輸液 LiDCO 体温管理 敗血症 MAP CVP PAカテ"},
  {"title":"腎・電解質・透析","url":"pages/video-lectures.html#vid-renal","desc":"動画講座集 › カテゴリ","keywords":"腎 電解質 透析 低ナトリウム 血液ガス"},
  {"title":"感染症・薬剤","url":"pages/video-lectures.html#vid-infection","desc":"動画講座集 › カテゴリ","keywords":"感染症 薬剤 抗菌薬 COVID"},
  {"title":"血液内科","url":"pages/video-lectures.html#vid-hematology","desc":"動画講座集 › カテゴリ","keywords":"血液内科 AML 造血幹細胞移植 リンパ腫 藤野"},
  {"title":"画像","url":"pages/video-lectures.html#vid-imaging","desc":"動画講座集 › カテゴリ","keywords":"画像 胸部X線 読影 石井"},

  // ── 疾患・項目別まとめ ──
  {"title":"疾患・項目別まとめ","url":"pages/disease-topics.html","desc":"疾患ごとの総説まとめ（by system形式）","keywords":"疾患 トピック 総説 まとめ by system"},
  {"title":"低ナトリウム血症（総説）","url":"pages/disease-topics/dt-hyponatremia.html","desc":"低Na血症の診断・治療の総説","keywords":"低ナトリウム 低Na SIADH 補正速度 ODS 尿浸透圧 尿Na 3%食塩水"},
  {"title":"緑膿菌感染症（総説）","url":"pages/disease-topics/dt-pa-infection.html","desc":"P. aeruginosa菌血症の特徴・BALANCE試験の知見・投与期間の考え方","keywords":"緑膿菌 Pseudomonas aeruginosa 菌血症 bacteremia 投与期間 BALANCE SHORTEN-2 7日 14日 MDR バイオフィルム"},

  // ── ICUセット ──
  {"title":"ICUセット","url":"pages/schedule-ward-work.html","desc":"ICUオーダーセットへのアクセス方法・セット登録一覧","keywords":"ICUセット セット展開 オーダー セット登録 カルテ アクセス"},
  {"title":"ICUセットへのアクセス方法","url":"pages/schedule-ward-work.html#ward-set-access","desc":"ICUセット › アクセス方法","keywords":"セット展開 右クリック フォルダー設定 アクセス"},
  {"title":"ICUセット登録一覧","url":"pages/schedule-ward-work.html#ward-icu-sets","desc":"ICUセット › 全セット一覧表","keywords":"セット一覧 点滴 内服 コメント 入室 退室 同意書 輸血 呼吸器 インスリン 経腸栄養 吸入 代行入力"},

  // ── 病棟業務 ──
  {"title":"病棟業務","url":"pages/schedule-ward-daily.html","desc":"カンファレンス後のルーチン業務・手技","keywords":"病棟業務 ルーチン 採血 レントゲン 点滴 内服 コメント Daily Chart"},
  {"title":"ICU入室時のTo Do List","url":"pages/schedule-ward-daily.html#ward-admission","desc":"病棟業務 › 入室時ToDo","keywords":"入室 入室時 セット展開 同意書 スコア入力 admission"},
  {"title":"ICU退室時のTo Do List","url":"pages/schedule-ward-daily.html#ward-discharge","desc":"病棟業務 › 退室時ToDo","keywords":"退室 退室時 内科退室 外科退室 コメント削除 PRN削除 申し送り"},

  // ── ICUのルール ──
  {"title":"ICUのルール","url":"pages/pre-rotation-todo.html","desc":"ICUの基本ルール","keywords":"ルール 規則"},
  {"title":"看護師への情報伝達","url":"pages/pre-rotation-todo.html#rule-point1","desc":"ICUのルール › ポイント①","keywords":"看護師 オーダーシート 口頭オーダー 情報伝達"},
  {"title":"手技について","url":"pages/pre-rotation-todo.html#rule-point2","desc":"ICUのルール › ポイント②","keywords":"手技 タイムアウト 30分 交代"},
  {"title":"定期処方とバンコマイシン","url":"pages/pre-rotation-todo.html#rule-point3","desc":"ICUのルール › ポイント③","keywords":"定期処方 バンコマイシン 木曜日 血中濃度"},
  {"title":"ICUセットから展開してオーダー","url":"pages/pre-rotation-todo.html#rule-point4","desc":"ICUのルール › ポイント④","keywords":"ICUセット オーダー エラー"},
  {"title":"ICUリーダーに情報共有","url":"pages/pre-rotation-todo.html#rule-point5","desc":"ICUのルール › ポイント⑤","keywords":"リーダー 情報共有 チャット 血液内科 総合診療科 心臓血管外科"},
  {"title":"時間外申請のルール","url":"pages/pre-rotation-todo.html#rule-overtime","desc":"ICUのルール","keywords":"時間外 残業 申請 80時間 打刻 自己研鑽"},
  {"title":"その他重要事項10点","url":"pages/pre-rotation-todo.html#rule-10points","desc":"ICUのルール","keywords":"十箇条 心得 感染防御 上級医報告 主科報告 カルテ 検査 重要事項"},
  {"title":"愛されローテーターになるために","url":"pages/pre-rotation-todo.html#rule-loved","desc":"ICUのルール › ＋α","keywords":"愛される 名前 駆けつけ プラスアルファ"},

  // ── チーム編成 ──
  {"title":"ICUのチーム編成","url":"pages/icu-team.html","desc":"日勤フォーメーションと各役割","keywords":"チーム編成 フォーメーション 組織 ICUリーダー 病床リーダー スタッフ ローテーター 病棟長 レジデント フェロー 研修医"},

  // ── ICU PASSPORT ──
  {"title":"ICU PASSPORT","url":"pages/icu-passport.html","desc":"ローテーション中のレクチャーシート","keywords":"パスポート レクチャーシート 学習 評価 修了 サイン 賞品"},
  {"title":"ICU PASSPORT レクチャーシート","url":"pages/icu-passport.html#passport-main","desc":"ICU PASSPORT › シート1","keywords":"レクチャー サイン 修了 賞品"},
  {"title":"10CVCs Challenge Pack","url":"pages/icu-passport.html#passport-cvcs","desc":"ICU PASSPORT › シート2","keywords":"CV PICC バスキャス ライン 10本 手技"},
  {"title":"TOP-10 ICU Essential Cases Pack","url":"pages/icu-passport.html#passport-cases","desc":"ICU PASSPORT › シート3","keywords":"疾患 10疾患 手技 経験 8症例"},
  {"title":"5 RRS or ICU Admission Pack","url":"pages/icu-passport.html#passport-rrs","desc":"ICU PASSPORT › シート4","keywords":"RRS 相談PHS 緊急入室 5症例"},

  // ── 強化パック ──
  {"title":"ラインパック","url":"pages/learning-packs.html","desc":"強化パック4種","keywords":"CV PICC バスキャス ライン 10本 手技"},
  {"title":"疾患パック","url":"pages/learning-packs.html","desc":"強化パック4種","keywords":"疾患 10疾患 手技 経験 8症例"},
  {"title":"相談PHSパック","url":"pages/learning-packs.html","desc":"強化パック4種","keywords":"PHS 相談 緊急入室 5症例"},
  {"title":"コンプリート賞","url":"pages/learning-packs.html","desc":"強化パック4種","keywords":"コンプリート 全達成 賞品"},

  // ── スケジュール系 ──
  {"title":"朝カンファレンス前の準備","url":"pages/schedule-morning-prep.html","desc":"7:00 日勤スケジュール","keywords":"朝カンファレンス 準備 7:00 日勤 朝"},
  {"title":"日勤への申し送り","url":"pages/schedule-morning-handover.html","desc":"7:00 夜勤→日勤","keywords":"日勤 申し送り 7:00 夜勤 ハンドオーバー 引き継ぎ"},
  {"title":"病棟業務","url":"pages/schedule-ward-work.html","desc":"9:00 日勤スケジュール","keywords":"病棟業務 9:00 日勤"},
  {"title":"ICU入室時のTo Do List","url":"pages/schedule-ward-work.html#ward-admission","desc":"病棟業務 › SECTION 1","keywords":"入室 セット展開 同意書 スコア 採血 レントゲン Admission Daily Chart"},
  {"title":"ICU退室時のTo Do List","url":"pages/schedule-ward-work.html#ward-discharge","desc":"病棟業務 › SECTION 2","keywords":"退室 内科 外科 デバイス抜去 A-line CVC Foley PRN 酸素コメント 申し送り"},
  {"title":"ICUカルテに関するSOS","url":"pages/schedule-ward-work.html#ward-karte","desc":"病棟業務 › SECTION 3","keywords":"カルテ ICUセット 同意書 入室時セット 退室時セット オーダー 輸血 血栓予防"},
  {"title":"半日出勤の日は退勤","url":"pages/schedule-half-day.html","desc":"12:00 半日出勤制度","keywords":"半日出勤 退勤 12:00 半日勤務"},
  {"title":"夜勤への申し送り","url":"pages/schedule-day-handover.html","desc":"16:00 日勤→夜勤","keywords":"夜勤 申し送り 16:00 日勤 ハンドオーバー 引き継ぎ"},
  {"title":"日勤からの申し送り","url":"pages/schedule-night-start.html","desc":"16:00 夜勤開始","keywords":"日勤 申し送り 16:00 夜勤 夜勤開始"},
  {"title":"随時対応（夜間）","url":"pages/schedule-oncall.html","desc":"夜間の随時対応","keywords":"随時対応 夜間 夜勤 オンコール 当直"},
  {"title":"海外教科書勉強会","url":"pages/schedule-weekly-textbook.html","desc":"隔週月曜 週間スケジュール","keywords":"海外教科書 勉強会 隔週 月曜 textbook"},

  // ── HIV日和見感染症ガイドライン ──
  {"title":"HIV感染者における日和見感染症 予防・治療ガイドライン","url":"pages/articles-gl-hiv-oi.html","desc":"CDC/NIH/HIVMA-IDSA Living Document — 28セクション全網羅","keywords":"HIV AIDS 日和見感染 OI クリプトコッカス PCP トキソプラズマ CMV MAC 結核 PML 梅毒 HSV VZV HBV HCV ヒストプラズマ タラロマイコシス IRIS ART CD4 カンジダ"},
  {"title":"HIV-OI クリプトコッカス髄膜炎の治療","url":"pages/articles-gl-hiv-oi.html#s-crypto-tx","desc":"HIV-OI GL › 第3章 クリプトコッカス","keywords":"クリプトコッカス 髄膜炎 L-AmB フルシトシン フルコナゾール 三相治療 誘導 固定 維持 ICP 頭蓋内圧 腰椎穿刺"},
  {"title":"HIV-OI PCP予防・治療","url":"pages/articles-gl-hiv-oi.html#s-pcp","desc":"HIV-OI GL › 第7章 PCP","keywords":"PCP Pneumocystis ニューモシスチス TMP-SMX CD4 200 補助ステロイド ペンタミジン ダプソン アトバコン"},
  {"title":"HIV-OI トキソプラズマ脳炎の治療","url":"pages/articles-gl-hiv-oi.html#s-toxoplasma","desc":"HIV-OI GL › 第8章 トキソプラズマ","keywords":"トキソプラズマ 脳炎 TE ピリメタミン スルファジアジン ロイコボリン TMP-SMX CD4 100"},
  {"title":"HIV-OI MAC疾患の治療","url":"pages/articles-gl-hiv-oi.html#s-mac","desc":"HIV-OI GL › 第6章 MAC","keywords":"MAC Mycobacterium avium クラリスロマイシン エタンブトール アジスロマイシン リファブチン CD4 50"},
  {"title":"HIV-OI 結核とART開始タイミング","url":"pages/articles-gl-hiv-oi.html#s-tb","desc":"HIV-OI GL › 第7章 結核","keywords":"結核 TB LTBI INH リファンピン RIF IRIS ART タイミング CD4 50 MDR XDR"},
  {"title":"HIV-OI CMV疾患（網膜炎・大腸炎・神経疾患）","url":"pages/articles-gl-hiv-oi.html#s-cmv","desc":"HIV-OI GL › 第4章 CMV","keywords":"CMV サイトメガロウイルス 網膜炎 大腸炎 食道炎 神経疾患 ガンシクロビル バルガンシクロビル ホスカルネット IRIS IRU CD4 50"},
  {"title":"HIV-OI HBV感染の治療","url":"pages/articles-gl-hiv-oi.html#s-hbv","desc":"HIV-OI GL › 第5章 HBV","keywords":"HBV B型肝炎 TDF TAF FTC テノホビル エムトリシタビン ART CD4 3TC 耐性"},
  {"title":"HIV-OI クリプトコッカスのART開始タイミング・IRIS","url":"pages/articles-gl-hiv-oi.html#s-crypto-art","desc":"HIV-OI GL › 第3章 ART/IRIS","keywords":"クリプトコッカス IRIS ART タイミング 早期 遅延 髄膜炎 死亡率"},

  // ── SSC 2026 ガイドライン ──
  {"title":"SSC 2026 敗血症・敗血症性ショック管理 国際ガイドライン","url":"pages/articles-gl-ssc2026.html","desc":"Surviving Sepsis Campaign 2026 国際ガイドライン","keywords":"SSC 敗血症 セプシス ショック 輸液 昇圧薬 抗菌薬 乳酸 MAP 蘇生"},
  {"title":"SSC 2026 第1章 スクリーニングと初期管理","url":"pages/articles-gl-ssc2026.html#ssc-ch1","desc":"SSC 2026 › 第1章","keywords":"SSC スクリーニング QI NEWS qSOFA EWS コードセプシス 血液培養 乳酸 輸液 昇圧薬 MAP 30mL 蘇生 ICU入室"},
  {"title":"SSC 2026 パフォーマンス改善・コードセプシス","url":"pages/articles-gl-ssc2026.html#ssc-s1","desc":"SSC 2026 第1章 › SECTION 1","keywords":"QI プログラム コードセプシス セプシスハドル スクリーニング 質改善"},
  {"title":"SSC 2026 スクリーニングツール：NEWS vs qSOFA","url":"pages/articles-gl-ssc2026.html#ssc-s2","desc":"SSC 2026 第1章 › SECTION 2","keywords":"NEWS NEWS2 MEWS SIRS qSOFA スクリーニング 感度 AUC 院外 院内"},
  {"title":"SSC 2026 血液培養・乳酸値","url":"pages/articles-gl-ssc2026.html#ssc-s4","desc":"SSC 2026 第1章 › SECTION 4","keywords":"血液培養 乳酸 lactate 抗菌薬前 採取 S.aureus カンジダ 繰り返し培養"},
  {"title":"SSC 2026 初期蘇生：輸液・末梢昇圧薬","url":"pages/articles-gl-ssc2026.html#ssc-s5","desc":"SSC 2026 第1章 › SECTION 5","keywords":"輸液 晶質液 30mL/kg 昇圧薬 ノルアドレナリン 末梢 中心静脈 蘇生"},
  {"title":"SSC 2026 MAP目標 65mmHg・高齢者60〜65mmHg","url":"pages/articles-gl-ssc2026.html#ssc-s6","desc":"SSC 2026 第1章 › SECTION 6","keywords":"MAP 65mmHg 血圧目標 高齢者 昇圧薬 ICU入室"},

  // SSC 2026 第2章
  {"title":"SSC 2026 第2章 感染症管理","url":"pages/articles-gl-ssc2026.html#ssc-ch2","desc":"SSC 2026 › 第2章","keywords":"SSC 感染症 抗菌薬 タイミング ソースコントロール MDR ESBL βラクタム 延長投与 de-escalation SDD PCT BALANCE BLING"},
  {"title":"SSC 2026 抗菌薬投与タイミング：1時間・3時間ルール","url":"pages/articles-gl-ssc2026.html#ssc-s2-1","desc":"SSC 2026 第2章 › SECTION 1","keywords":"抗菌薬 タイミング 1時間 3時間 敗血症性ショック 院外 PCT"},
  {"title":"SSC 2026 ソースコントロール：6時間以内の介入","url":"pages/articles-gl-ssc2026.html#ssc-s2-2","desc":"SSC 2026 第2章 › SECTION 2","keywords":"ソースコントロール 感染源 ドレナージ デブリードマン 6時間"},
  {"title":"SSC 2026 βラクタム延長投与（BLING III試験）","url":"pages/articles-gl-ssc2026.html#ssc-s2-5","desc":"SSC 2026 第2章 › SECTION 5","keywords":"βラクタム 延長投与 prolonged infusion BLING III PK/PD TDM 時間依存性"},
  {"title":"SSC 2026 De-escalation・抗菌薬投与期間（BALANCE試験）","url":"pages/articles-gl-ssc2026.html#ssc-s2-6","desc":"SSC 2026 第2章 › SECTION 6","keywords":"de-escalation 投与期間 7日 14日 BALANCE PCT ADAPT-Sepsis 短期間"},

  // SSC 2026 第3章
  {"title":"SSC 2026 第3章 血行動態管理","url":"pages/articles-gl-ssc2026.html#ssc-ch3","desc":"SSC 2026 › 第3章","keywords":"SSC 輸液 晶質液 生食 バランス HES ゼラチン アルブミン 昇圧薬 ノルアドレナリン バソプレシン PLR SVV 乳酸 CRT ドブタミン"},
  {"title":"SSC 2026 輸液の選択：バランス晶質液・HES禁忌","url":"pages/articles-gl-ssc2026.html#ssc-s3-2","desc":"SSC 2026 第3章 › SECTION 2","keywords":"晶質液 バランス 生理食塩水 生食 HES スターチ ゼラチン アルブミン SMART BaSICS PLUS 輸液"},
  {"title":"SSC 2026 蘇生エンドポイント：乳酸値・毛細血管再充填時間（CRT）","url":"pages/articles-gl-ssc2026.html#ssc-s3-4","desc":"SSC 2026 第3章 › SECTION 4","keywords":"乳酸 lactate CRT 毛細血管再充填 ANDROMEDA-SHOCK 蘇生エンドポイント"},
  {"title":"SSC 2026 昇圧薬：ノルエピネフリン→バソプレシン追加","url":"pages/articles-gl-ssc2026.html#ssc-s3-5","desc":"SSC 2026 第3章 › SECTION 5","keywords":"ノルエピネフリン ノルアドレナリン バソプレシン アンジオテンシン エピネフリン 昇圧薬 テルリプレシン"},

  // SSC 2026 第4章
  {"title":"SSC 2026 第4章 呼吸管理","url":"pages/articles-gl-ssc2026.html#ssc-ch4","desc":"SSC 2026 › 第4章","keywords":"SSC 呼吸 HFNC NIV NIPPV SpO2 酸素 ARDS 人工呼吸 一回換気量 PEEP 腹臥位 覚醒 ECMO"},
  {"title":"SSC 2026 HFNC vs NIV vs 通常酸素療法","url":"pages/articles-gl-ssc2026.html#ssc-s4-3","desc":"SSC 2026 第4章 › SECTION 3","keywords":"HFNC NIV NIPPV 高流量鼻カニュラ 非侵襲的 酸素療法 急性低酸素性呼吸不全"},
  {"title":"SSC 2026 ARDS管理：低TV・高PEEP・腹臥位","url":"pages/articles-gl-ssc2026.html#ssc-s4-5","desc":"SSC 2026 第4章 › SECTION 5","keywords":"ARDS 一回換気量 TV PEEP 腹臥位 prone NMBA プラトー圧 低肺傷害"},

  // SSC 2026 第5章
  {"title":"SSC 2026 第5章 補助療法・支持療法","url":"pages/articles-gl-ssc2026.html#ssc-ch5","desc":"SSC 2026 › 第5章","keywords":"SSC ステロイド 解熱薬 ビタミンC IVIG 血液浄化 PPI VTE 輸血 インスリン 血糖 RRT 輸液除去"},
  {"title":"SSC 2026 ステロイド：敗血症性ショックへのhydrocortisone","url":"pages/articles-gl-ssc2026.html#ssc-s5-1","desc":"SSC 2026 第5章 › SECTION 1","keywords":"ステロイド hydrocortisone コルチゾール ショック 200mg 7日 ADRENAL"},
  {"title":"SSC 2026 PPI：ストレス潰瘍予防（REVISE試験）","url":"pages/articles-gl-ssc2026.html#ssc-s5-3","desc":"SSC 2026 第5章 › SECTION 3","keywords":"PPI 潰瘍予防 ストレス潰瘍 GI出血 REVISE プロトンポンプ"},

  // SSC 2026 第6章
  {"title":"SSC 2026 第6章 Goals of Care・長期アウトカム","url":"pages/articles-gl-ssc2026.html#ssc-ch6","desc":"SSC 2026 › 第6章","keywords":"SSC GoC ゴールオブケア 緩和ケア 退院 PICS 長期後遺症 リハビリ メンタルヘルス 認知機能 フォローアップ"},
  {"title":"SSC 2026 PICS（集中治療後症候群）の長期管理","url":"pages/articles-gl-ssc2026.html#ssc-s6-6","desc":"SSC 2026 第6章 › SECTION 6","keywords":"PICS post ICU syndrome 長期後遺症 リハビリ メンタルヘルス 認知機能 フォローアップ QOL"},

  // 低ナトリウム血症ガイドライン 2014（ESICM/ESE/ERA-EDTA）
  {"title":"低ナトリウム血症 診断・治療ガイドライン（ESICM/ESE/ERA-EDTA 2014）","url":"pages/articles-gl-hn2014.html","desc":"低ナトリウム血症ガイドライン概要","keywords":"低ナトリウム血症 低Na血症 SIAD SIADH バソプレシン AVP 高張食塩水 ODS 浸透圧性脱髄 電解質 ESICM ESE ERA-EDTA 3%食塩水 トルバプタン vaptan 輸液制限 尿浸透圧 尿ナトリウム"},
  {"title":"低ナトリウム血症 第1章 病態生理・分類・診断","url":"注目論文ガイドラインのまとめ/hn-chapter1.html#hn-ch1","desc":"低ナトリウム血症ガイドライン › 第1章","keywords":"低ナトリウム血症 病態生理 分類 急性 慢性 48時間 軽度 中等度 重度 profound 症状 重篤 moderately severe 診断 アルゴリズム 尿浸透圧 尿ナトリウム 電解質"},
  {"title":"低ナトリウム血症 疫学と病態生理（AVP・脳適応）","url":"注目論文ガイドラインのまとめ/hn-chapter1.html#hn-s1","desc":"低ナトリウム血症ガイドライン 第1章 › SECTION 1","keywords":"疫学 15-20% 救急 バソプレシン AVP ADH 脳浮腫 脳適応 ODS 浸透圧性脱髄 osmotic demyelination"},
  {"title":"低ナトリウム血症の分類（重症度・期間・症状）","url":"注目論文ガイドラインのまとめ/hn-chapter1.html#hn-s2","desc":"低ナトリウム血症ガイドライン 第1章 › SECTION 2","keywords":"分類 軽度 130 中等度 125 重度 profound 急性 慢性 48時間 重篤 seizure 昏睡 moderately severe 嘔気 頭痛"},
  {"title":"非低張性低ナトリウム血症の除外（高血糖補正・偽性低Na）","url":"注目論文ガイドラインのまとめ/hn-chapter1.html#hn-s3","desc":"低ナトリウム血症ガイドライン 第1章 › SECTION 3","keywords":"偽性低ナトリウム血症 高血糖 マンニトール グリシン 浸透圧 補正ナトリウム pseudohyponatremia isotonic hypertonic"},
  {"title":"低ナトリウム血症の診断アルゴリズム（尿浸透圧・尿Na）","url":"注目論文ガイドラインのまとめ/hn-chapter1.html#hn-s4","desc":"低ナトリウム血症ガイドライン 第1章 › SECTION 4","keywords":"診断アルゴリズム 尿浸透圧 100 尿ナトリウム 30 多飲 低溶質 心不全 肝硬変 利尿薬 腎不全 SIAD 副腎不全 甲状腺 hypovolaemia euvolaemia hypervolaemia"},
  {"title":"SIAD（抗利尿ホルモン不適切分泌症候群）の診断基準","url":"注目論文ガイドラインのまとめ/hn-chapter1.html#hn-s5","desc":"低ナトリウム血症ガイドライン 第1章 › SECTION 5","keywords":"SIAD SIADH 診断基準 Bartter Schwartz 浸透圧 275 尿浸透圧 100 euvolemia 尿ナトリウム 30 甲状腺 副腎 悪性腫瘍 薬剤 CNS 肺炎"},
  {"title":"低ナトリウム血症 第2章 治療","url":"注目論文ガイドラインのまとめ/hn-chapter2.html#hn-ch2","desc":"低ナトリウム血症ガイドライン › 第2章","keywords":"低ナトリウム血症 治療 3%食塩水 高張食塩水 補正速度 ODS 浸透圧性脱髄 輸液制限 SIAD 心不全 肝硬変 デスモプレシン トルバプタン 尿素"},
  {"title":"低ナトリウム血症 治療アルゴリズム・補正速度制限","url":"注目論文ガイドラインのまとめ/hn-chapter2.html#hn-tx-overview","desc":"低ナトリウム血症ガイドライン 第2章 › SECTION 1","keywords":"補正速度 10mmol 8mmol ODS 浸透圧性脱髄 24時間 治療アルゴリズム 症状主導 高張食塩水"},
  {"title":"重篤な低ナトリウム血症の治療（痙攣・昏睡）：7.1","url":"注目論文ガイドラインのまとめ/hn-chapter2.html#hn-tx-severe","desc":"低ナトリウム血症ガイドライン 第2章 › SECTION 2","keywords":"重篤 severe 痙攣 昏睡 GCS 呼吸抑制 3%食塩水 150ml 20分 5mmol/L 高張食塩水 即時"},
  {"title":"中等度症状の低ナトリウム血症：嘔気・混乱・頭痛（7.2）","url":"注目論文ガイドラインのまとめ/hn-chapter2.html#hn-tx-moderate","desc":"低ナトリウム血症ガイドライン 第2章 › SECTION 3","keywords":"中等度 moderately severe 嘔気 混乱 頭痛 3%食塩水 150ml 原因特異的治療 診断"},
  {"title":"急性低ナトリウム血症（48h未満・無症状）の管理（7.3）","url":"注目論文ガイドラインのまとめ/hn-chapter2.html#hn-tx-acute","desc":"低ナトリウム血症ガイドライン 第2章 › SECTION 4","keywords":"急性 48時間 無症状 3%食塩水 原因除去 サイアザイド SSRI 運動後 術後"},
  {"title":"慢性低ナトリウム血症の管理：SIAD・HF・低血圧型（7.4）","url":"注目論文ガイドラインのまとめ/hn-chapter2.html#hn-tx-chronic","desc":"低ナトリウム血症ガイドライン 第2章 › SECTION 5","keywords":"慢性 SIAD 輸液制限 尿素 フロセミド NaCl 心不全 肝硬変 ネフローゼ 生食 0.9% 原因特異的 vaptan トルバプタン デメクロサイクリン 禁忌"},
  {"title":"低ナトリウム血症 補正過剰への対処・ODS予防（7.5）","url":"注目論文ガイドラインのまとめ/hn-chapter2.html#hn-tx-overcorr","desc":"低ナトリウム血症ガイドライン 第2章 › SECTION 6","keywords":"補正過剰 overcorrection ODS 浸透圧性脱髄 デスモプレシン 2mcg 自由水 5%ブドウ糖 アルコール 肝疾患 サイアザイド 低カリウム"},

  // KDIGO 2026 AKI/AKD ガイドライン
  {"title":"KDIGO 2026 AKI/AKD ガイドライン（Public Review Draft）","url":"pages/articles-gl-kdigo-aki2026.html","desc":"KDIGO 2026 AKI/AKD ガイドライン概要","keywords":"AKI 急性腎障害 AKD 急性腎疾患 KDIGO 2026 RRT 腎代替療法 バイオマーカー CRRT フロセミドストレステスト KeGFR 造影剤 薬剤性腎障害 シスタチンC CKD フォローアップ"},
  {"title":"KDIGO 2026 第1章 AKI/AKD定義・ステージング","url":"pages/articles-gl-kdigo-aki2026.html#aki-ch1","desc":"KDIGO 2026 › 第1章","keywords":"AKI定義 構造的基準 シスタチンC 3軸分類 C/U/B staging ステージング 一過性AKI 持続性AKI AKD定義 解消定義 回復"},
  {"title":"AKI定義の2026年改訂：構造的基準の追加","url":"pages/articles-gl-kdigo-aki2026.html#aki1-s1","desc":"KDIGO 2026 第1章 › SECTION 1","keywords":"AKI定義 2026 構造的基準 structural criteria 腎萎縮 線維化 画像 生検 シスタチンC 2B クレアチニン 尿量 48時間 7日 1.5倍"},
  {"title":"AKIのステージング（3軸分類）","url":"pages/articles-gl-kdigo-aki2026.html#aki1-s2","desc":"KDIGO 2026 第1章 › SECTION 2","keywords":"ステージング staging 3軸 C U B クレアチニン 尿量 バイオマーカー TIMP-2 IGFBP7 NGAL KIM-1 一過性 持続性 transient persistent stage 1 2 3"},
  {"title":"AKDの定義とAKI解消の定義","url":"pages/articles-gl-kdigo-aki2026.html#aki1-s3","desc":"KDIGO 2026 第1章 › SECTION 3","keywords":"AKD 急性腎疾患 定義 解消 resolution 7日 90日 回復 complete partial CKD 移行 フォローアップ"},
  {"title":"KDIGO 2026 第2章 リスク層別化・診断","url":"pages/articles-gl-kdigo-aki2026.html#aki-ch2","desc":"KDIGO 2026 › 第2章","keywords":"リスク予測 電子アラート 腎機能評価 FST フロセミドストレステスト KeGFR バイオマーカー 尿沈渣 FeNa 腎生検 診断"},
  {"title":"リスク予測モデルと電子アラート（KDIGO 2026）","url":"pages/articles-gl-kdigo-aki2026.html#aki2-s1","desc":"KDIGO 2026 第2章 › SECTION 1","keywords":"リスク予測 電子アラート AKI alert 割り込みアラート interruptive 1B 機械学習 AKIWarning AKI-BERT eGFR urine output"},
  {"title":"腎機能評価：FST と KeGFR","url":"pages/articles-gl-kdigo-aki2026.html#aki2-s2","desc":"KDIGO 2026 第2章 › SECTION 2","keywords":"FST フロセミドストレステスト furosemide stress test 1mg/kg 200ml 2時間 KeGFR kinetic eGFR 2B 高リスク RRT予測 急性動態"},
  {"title":"バイオマーカーの臨床的活用（KDIGO 2026）","url":"pages/articles-gl-kdigo-aki2026.html#aki2-s3","desc":"KDIGO 2026 第2章 › SECTION 3","keywords":"バイオマーカー biomarker TIMP-2 IGFBP7 NephroCheck NGAL KIM-1 CCL14 尿細管ストレス 細胞周期停止 AKI進行予測 2B"},
  {"title":"AKI診断的評価：尿沈渣・FeNa・腎生検","url":"pages/articles-gl-kdigo-aki2026.html#aki2-s4","desc":"KDIGO 2026 第2章 › SECTION 4","keywords":"尿沈渣 顆粒円柱 泥茶色円柱 muddy brown cast FeNa フラクショナルナトリウム排泄 AT-score ATI 腎生検 2B 尿細管障害"},
  {"title":"KDIGO 2026 第3章 AKI予防・治療","url":"pages/articles-gl-kdigo-aki2026.html#aki-ch3","desc":"KDIGO 2026 › 第3章","keywords":"輸液管理 生理食塩水 緩衝液 MAP 血行動態管理 ノルアドレナリン 利尿薬 腎保護バンドル HRS TLS 横紋筋融解症 栄養管理"},
  {"title":"輸液管理（緩衝液vs生食・コロイド禁忌）","url":"pages/articles-gl-kdigo-aki2026.html#aki3-s1","desc":"KDIGO 2026 第3章 › SECTION 1","keywords":"輸液 緩衝液 balanced crystalloid 乳酸リンゲル PlasmaLyte 生理食塩水 高塩素血症 HES ヒドロキシエチルデンプン アルブミン 1B 禁忌"},
  {"title":"血行動態管理：MAP目標と昇圧剤","url":"pages/articles-gl-kdigo-aki2026.html#aki3-s2","desc":"KDIGO 2026 第3章 › SECTION 2","keywords":"MAP 65mmHg 目標血圧 2B ノルアドレナリン ドパミン 低用量ドパミン 1A 腎保護バンドル multicomponent bundle 1B 血糖管理 腎毒性薬剤中止"},
  {"title":"利尿薬の適正使用","url":"pages/articles-gl-kdigo-aki2026.html#aki3-s3","desc":"KDIGO 2026 第3章 › SECTION 3","keywords":"利尿薬 フロセミド ループ利尿薬 体液過剰 volume overload 2B ボーラス 持続投与 AKI予防禁忌 マンニトール 高浸透圧"},
  {"title":"特殊病態：HRS・TLS・横紋筋融解症","url":"pages/articles-gl-kdigo-aki2026.html#aki3-s4","desc":"KDIGO 2026 第3章 › SECTION 4","keywords":"HRS 肝腎症候群 テルリプレシン terlipressin ノルアドレナリン アルブミン TLS 腫瘍崩壊症候群 ラスブリカーゼ rasburicase 1B 横紋筋融解症 尿アルカリ化"},
  {"title":"その他の治療（心臓手術・栄養管理）","url":"pages/articles-gl-kdigo-aki2026.html#aki3-s5","desc":"KDIGO 2026 第3章 › SECTION 5","keywords":"心臓手術 CABG 心肺バイパス 経口栄養 経静脈栄養 タンパク制限禁忌 CRRT 2.5g/kg アミノ酸 1.5-2.5g/kg"},
  {"title":"KDIGO 2026 第4章 薬剤性AKI","url":"pages/articles-gl-kdigo-aki2026.html#aki-ch4","desc":"KDIGO 2026 › 第4章","keywords":"薬剤性AKI 造影剤 CA-AKI NSAID アミノグリコシド バンコマイシン RASi ACE阻害薬 ARB KeGFR 薬剤量調整 シックデイ"},
  {"title":"薬剤の分類と腎保護スチュワードシップ","url":"pages/articles-gl-kdigo-aki2026.html#aki4-s1","desc":"KDIGO 2026 第4章 › SECTION 1","keywords":"薬剤分類 腎毒性 nephrotoxin スチュワードシップ stewardship 1C アミノグリコシド 一日一回投与 TDM バンコマイシン AUC 持続投与 シスプラチン"},
  {"title":"造影剤関連AKI（CA-AKI）の予防","url":"pages/articles-gl-kdigo-aki2026.html#aki4-s2","desc":"KDIGO 2026 第4章 › SECTION 2","keywords":"造影剤 CA-AKI contrast associated AKI 予防 生理食塩水 0.9% 1B NAC N-アセチルシステイン 炭酸水素ナトリウム アスコルビン酸 予防的透析 禁忌"},
  {"title":"AKI時の薬剤量調整・シックデイプロトコル","url":"pages/articles-gl-kdigo-aki2026.html#aki4-s3","desc":"KDIGO 2026 第4章 › SECTION 3","keywords":"薬剤量調整 KeGFR RASi ACE ARB 中止 再開 2B シックデイ sick day protocol 2D メトホルミン NSAID 利尿薬 脱水"},
  {"title":"KDIGO 2026 第5章 腎代替療法（RRT）","url":"pages/articles-gl-kdigo-aki2026.html#aki-ch5","desc":"KDIGO 2026 › 第5章","keywords":"RRT 腎代替療法 CRRT 血液透析 IHD 腹膜透析 PD 開始タイミング 用量 抗凝固 クエン酸 ヘパリン 中止 離脱"},
  {"title":"RRT開始のタイミング（待機的戦略）","url":"pages/articles-gl-kdigo-aki2026.html#aki5-s1","desc":"KDIGO 2026 第5章 › SECTION 1","keywords":"RRT開始 タイミング 待機的 deferred 1C STARRT-AKI IDEAL-ICU 緊急 emergency 高カリウム 代謝性アシドーシス 肺水腫 pH 7.2"},
  {"title":"RRTモダリティの選択","url":"pages/articles-gl-kdigo-aki2026.html#aki5-s2","desc":"KDIGO 2026 第5章 › SECTION 2","keywords":"CRRT 持続的腎代替療法 IHD 間欠的血液透析 PD 腹膜透析 血行動態不安定 2C SLED sustained low efficiency PIRRT 小児"},
  {"title":"RRTの用量（20-25 ml/kg/h）","url":"pages/articles-gl-kdigo-aki2026.html#aki5-s3","desc":"KDIGO 2026 第5章 › SECTION 3","keywords":"CRRT 用量 dose 20ml/kg/h 25ml/kg/h 1B HVHF 高容量血液濾過 禁忌 処方量 供給量 ダウンタイム"},
  {"title":"抗凝固：クエン酸が第一選択","url":"pages/articles-gl-kdigo-aki2026.html#aki5-s4","desc":"KDIGO 2026 第5章 › SECTION 4","keywords":"クエン酸 regional citrate anticoagulation RCA ヘパリン 1B 出血リスク 肝不全 乳酸アシドーシス イオン化カルシウム モニタリング"},
  {"title":"RRTの中止と離脱","url":"pages/articles-gl-kdigo-aki2026.html#aki5-s5","desc":"KDIGO 2026 第5章 › SECTION 5","keywords":"RRT中止 離脱 中止基準 尿量 450ml/日 2300ml/日 利尿薬 CrCl 23ml/min 自然回復 腎回復"},
  {"title":"KDIGO 2026 第6章 AKI後フォローアップ","url":"pages/articles-gl-kdigo-aki2026.html#aki-ch6","desc":"KDIGO 2026 › 第6章","keywords":"フォローアップ CKD AKI後 退院後 RASi SGLT2阻害薬 GLP-1受容体作動薬 MRA 3ヶ月 腎機能評価 リスク層別化"},
  {"title":"退院後の計画的フォローアップ","url":"pages/articles-gl-kdigo-aki2026.html#aki6-s1","desc":"KDIGO 2026 第6章 › SECTION 1","keywords":"フォローアップ 1B 退院後 計画的 腎臓専門医 紹介基準 リスク層別化 2D AKI後 回復"},
  {"title":"退院後の薬剤管理（RASi・腎保護薬）","url":"pages/articles-gl-kdigo-aki2026.html#aki6-s2","desc":"KDIGO 2026 第6章 › SECTION 2","keywords":"RASi 再開 1B ACE阻害薬 ARB SGLT2阻害薬 GLP-1受容体作動薬 MRA ミネラルコルチコイド受容体拮抗薬 フィネレノン 心腎連関 薬剤再評価"},
  {"title":"CKD評価とRRT離脱後のフォロー","url":"pages/articles-gl-kdigo-aki2026.html#aki6-s3","desc":"KDIGO 2026 第6章 › SECTION 3","keywords":"CKD 評価 3ヶ月 eGFR 尿蛋白 尿アルブミン RRT離脱後 腎機能回復 AKD CKD移行 腎生検 適応"},

  // ── SHEA/IDSA 2021 CDI管理ガイドライン Focused Update ──
  {"title":"SHEA/IDSA 2021 CDI管理ガイドライン Focused Update — フィダキソマイシン / ベズロトクスマブ / 再発予防","url":"pages/articles-gl-cdi-shea2021.html","desc":"SHEA/IDSA 2021 › 概要","keywords":"CDI Clostridioides difficile クロストリジオイデス ディフィシル C. difficile フィダキソマイシン fidaxomicin バンコマイシン vancomycin ベズロトクスマブ bezlotoxumab 再発 recurrence FMT 糞便微生物移植 fecal microbiota transplantation メトロニダゾール metronidazole リファキシミン rifaximin 劇症型 fulminant 抗菌薬関連下痢 CDAD SHEA IDSA 2021 Johnson CID Clinical Infectious Diseases"},
  {"title":"CDI重症度分類・治療推奨一覧（Table 1）","url":"pages/articles-gl-cdi-shea2021.html#cdi-table1","desc":"SHEA/IDSA 2021 › 治療推奨一覧","keywords":"非重症 WBC 15000 クレアチニン 1.5 劇症型 低血圧 ショック イレウス 巨大結腸 megacolon フィダキソマイシン 200mg バンコマイシン 125mg テーパー パルス FMT 初回 再発 bezlotoxumab 10mg/kg"},
  {"title":"PICO 1：初回CDIにおけるフィダキソマイシン vs バンコマイシン","url":"pages/articles-gl-cdi-shea2021.html#cdi-ch1","desc":"SHEA/IDSA 2021 › PICO 1","keywords":"初回CDI フィダキソマイシン バンコマイシン 条件付き推奨 中程度 持続的治療反応 sustained response RR 1.16 1673例 4RCT 再発抑制 初期治癒"},
  {"title":"PICO 1エビデンス — 1,673例・4RCT（Table 2）","url":"pages/articles-gl-cdi-shea2021.html#cdi-pico1-evidence","desc":"SHEA/IDSA 2021 › PICO 1エビデンス","keywords":"1673 4RCT Table 2 RR 1.16 1.09 1.24 持続的治療反応 101/1000 CDI治癒率 全死亡 有害事象 moderate GRADE"},
  {"title":"PICO 2：再発CDIにおけるフィダキソマイシン（標準・延長パルス）vs バンコマイシン","url":"pages/articles-gl-cdi-shea2021.html#cdi-ch2","desc":"SHEA/IDSA 2021 › PICO 2","keywords":"再発CDI recurrent CDI フィダキソマイシン 延長パルス extended-pulsed バンコマイシン 条件付き推奨 低確実性 RR 1.27 253例 3RCT 30日 90日 テーパー パルス リファキシミン FMT"},
  {"title":"PICO 3：ベズロトクスマブの適応と安全性（Table 4）","url":"pages/articles-gl-cdi-shea2021.html#cdi-ch3","desc":"SHEA/IDSA 2021 › PICO 3","keywords":"ベズロトクスマブ bezlotoxumab 10mg/kg 6ヶ月以内 再発リスク 65歳 免疫抑制 重症 CHF うっ血性心不全 FDA警告 RR 0.62 1246例 1RCT ICC後再発 毒素B toxin B モノクローナル抗体"},

  // ── IDSA 2017 医療関連脳室炎・髄膜炎ガイドライン ──
  {"title":"IDSA 2017 医療関連脳室炎・髄膜炎（HAVM）ガイドライン — 診断・治療・予防","url":"pages/articles-gl-idsa-havm2017.html","desc":"IDSA 2017 › 概要","keywords":"医療関連髄膜炎 脳室炎 HAVM healthcare-associated ventriculitis meningitis CSFシャント EVD 外部脳室ドレーン 髄腔内ポンプ DBS 脳深部刺激 開頭術 頭部外傷 IDSA 2017 Tunkel バンコマイシン 経験的抗菌薬"},
  {"title":"HAVM 背景・デバイス別感染率","url":"pages/articles-gl-idsa-havm2017.html#havm-bg","desc":"IDSA 2017 › 背景","keywords":"CSFシャント感染率 4-17% EVD 11.4 1000カテーテル日 CoNS S. epidermidis MRSA グラム陰性桿菌 バイオフィルム 術中汚染 市中髄膜炎との違い"},
  {"title":"HAVM デバイス別症状・徴候","url":"pages/articles-gl-idsa-havm2017.html#havm-symptoms","desc":"IDSA 2017 › 症状","keywords":"VPシャント 腹膜炎 VPl胸膜炎 VAシャント 菌血症 90% 血培陽性 糸球体腎炎 シャント腎炎 EVD 精神状態変化 発熱 CSF白血球 175"},
  {"title":"HAVM CSF所見の解釈と培養","url":"pages/articles-gl-idsa-havm2017.html#havm-csf","desc":"IDSA 2017 › CSF所見","keywords":"CSF培養 P. acnes 10日間保持 グラム染色 陰性 除外不可 血液培養 VAシャント 正常CSF 感染除外不可 Lozier分類 汚染 定着 脳室炎 CDC NHSN"},
  {"title":"HAVM CSF確定検査（乳酸・プロカルシトニン・PCR・真菌マーカー）","url":"pages/articles-gl-idsa-havm2017.html#havm-tests","desc":"IDSA 2017 › 確定検査","keywords":"CSF乳酸 lactate 4 mmol カットオフ プロカルシトニン 1 ng/mL β-D-グルカン 80 pg/mL ガラクトマンナン PCR 核酸増幅 真菌 Candida Aspergillus"},
  {"title":"HAVM 神経画像検査","url":"pages/articles-gl-idsa-havm2017.html#havm-imaging","desc":"IDSA 2017 › 画像","keywords":"MRI ガドリニウム 拡散強調画像 DWI FLAIR 脳室炎 CT 腹部超音波 VPシャント 腹部症状 CSF局在"},
  {"title":"HAVM 経験的抗菌薬療法","url":"pages/articles-gl-idsa-havm2017.html#havm-empiric","desc":"IDSA 2017 › 経験的療法","keywords":"バンコマイシン 抗緑膿菌 βラクタム セフェピム セフタジジム メロペネム 経験的 トラフ 15 20 μg/mL アズトレオナム シプロフロキサシン 耐性菌"},
  {"title":"HAVM 標的抗菌薬療法（菌種別）","url":"pages/articles-gl-idsa-havm2017.html#havm-targeted","desc":"IDSA 2017 › 標的療法","keywords":"MSSA ナフシリン オキサシリン MRSA バンコマイシン MIC 1 μg/mL リネゾリド ダプトマイシン TMP-SMX P. acnes ペニシリンG 緑膿菌 セフェピム ESBL メロペネム Acinetobacter コリスチン ポリミキシン Candida アムホテリシン フルシトシン Aspergillus ボリコナゾール リファンピシン"},
  {"title":"HAVM 用量表（成人、正常腎機能）","url":"pages/articles-gl-idsa-havm2017.html#havm-targeted","desc":"IDSA 2017 › 推奨用量","keywords":"バンコマイシン 30-60 mg/kg セフェピム 6g セフタジジム メロペネム 6g シプロフロキサシン リネゾリド 1200mg TMP-SMX リポソームアムホテリシン ボリコナゾール 8mg/kg トラフ"},
  {"title":"HAVM 脳室内（IVT）抗菌薬投与","url":"pages/articles-gl-idsa-havm2017.html#havm-ivt","desc":"IDSA 2017 › 脳室内投与","keywords":"脳室内投与 intraventricular IVT クランプ 15-60分 バンコマイシン 5-20mg ゲンタマイシン アミカシン コリスチン ポリミキシン MIC 10-20倍 脳室サイズ EVD排液量 保存料不含"},
  {"title":"HAVM 治療期間","url":"pages/articles-gl-idsa-havm2017.html#havm-duration","desc":"IDSA 2017 › 治療期間","keywords":"CoNS P. acnes 10日間 10-14日間 S. aureus グラム陰性桿菌 21日間 培養陽性 最終陽性 10-14日継続"},
  {"title":"HAVM デバイス抜去の役割","url":"pages/articles-gl-idsa-havm2017.html#havm-removal","desc":"IDSA 2017 › デバイス抜去","keywords":"シャント抜去 EVD除去 髄腔内ポンプ除去 DBS除去 外部脳室ドレーン置換 保存的管理 成功率34-36% バイオフィルム"},
  {"title":"HAVM 治療反応モニタリングとシャント再挿入","url":"pages/articles-gl-idsa-havm2017.html#havm-monitor","desc":"IDSA 2017 › モニタリング・再挿入","keywords":"CSF培養 陰性化 モニタリング 炎症マーカー CRP ESR 無用 再挿入 3日目 7日後 10日後 CoNS P. acnes S. aureus グラム陰性桿菌 休薬期間 不要"},
  {"title":"HAVM 予防：周術期抗菌薬・抗菌薬含浸カテーテル・EVD管理","url":"pages/articles-gl-idsa-havm2017.html#havm-prev-shunt","desc":"IDSA 2017 › 予防","keywords":"周術期予防的抗菌薬 抗菌薬含浸カテーテル ミノサイクリン リファンピシン 50%減少 オッズ比 0.52 長期予防的抗菌薬 禁忌 耐性菌 MRSA Candida 固定間隔交換 不要 標準化プロトコル"},
  {"title":"HAVM 開頭術・頭蓋底骨折後の予防","url":"pages/articles-gl-idsa-havm2017.html#havm-prev-neuro","desc":"IDSA 2017 › 外傷後予防","keywords":"開頭術 周術期抗菌薬 頭蓋底骨折 CSF漏 予防的抗菌薬 推奨しない Cochrane 漏孔修復 7日 肺炎球菌ワクチン PCV13 PPSV23"},

  // ── IDSA 2025 複雑性UTIガイドライン ──
  {"title":"IDSA 2025 複雑性尿路感染症（cUTI）管理ガイドライン — 経験的抗菌薬 / IV-to-oral転換 / 投与期間","url":"pages/articles-gl-uti-idsa2025.html","desc":"IDSA 2025 › 概要","keywords":"尿路感染症 UTI cUTI 複雑性UTI IDSA 腎盂腎炎 pyelonephritis CAUTI カテーテル関連UTI 抗菌薬耐性 フルオロキノロン ST合剤 TMP-SMX ニトロフラントイン Enterobacterales IV-to-oral 投与期間 GRADE"},
  {"title":"cUTI新分類 — 「解剖学的異常」から「全身症状の有無」へ","url":"pages/articles-gl-uti-idsa2025.html#uti-ch0","desc":"IDSA 2025 › 前提：新分類","keywords":"複雑性UTI cUTI 非複雑性UTI uUTI 分類 全身症状 発熱 CVA叩打痛 悪寒 戦慄 血行動態不安定 CAUTI 糖尿病 免疫不全 腎盂腎炎 解剖学的異常"},
  {"title":"CQ1：経験的抗菌薬の選択 — 推奨一覧（重症度別）","url":"pages/articles-gl-uti-idsa2025.html#uti-cq1-rec","desc":"IDSA 2025 CQ1 › 推奨一覧","keywords":"経験的抗菌薬 敗血症 敗血症性ショック 第3世代セファロスポリン カルバペネム PIPC TAZ フルオロキノロン TMP-SMX ニトロフラントイン 不適切 Enterobacterales"},
  {"title":"4ステップアプローチ（経験的抗菌薬選択）","url":"pages/articles-gl-uti-idsa2025.html#uti-4step","desc":"IDSA 2025 CQ1 › 4ステップ","keywords":"4ステップ 重症度 SOFA qSOFA 耐性リスク 先行培養 フルオロキノロン使用歴 12ヶ月 患者固有 アンチビオグラム 感受性率 90% 80% 経験的選択"},
  {"title":"各薬剤クラスの位置づけとエビデンス","url":"pages/articles-gl-uti-idsa2025.html#uti-drugs","desc":"IDSA 2025 CQ1 › 薬剤別エビデンス","keywords":"セフトリアキソン PIPC/TAZ ピペラシリン タゾバクタム フルオロキノロン カルバペネム ESBL 耐性 経口抗菌薬 CAZ-AVI セフィデロコル プラゾミシン 新規BLBLI"},
  {"title":"確定治療とde-escalation（cUTI）","url":"pages/articles-gl-uti-idsa2025.html#uti-definitive","desc":"IDSA 2025 CQ1 › 確定治療","keywords":"確定治療 de-escalation ナローイング スチュワードシップ 感受性既知 抗菌薬スペクトラム 腸内細菌科 緑膿菌 CRE ESBL 培養結果"},
  {"title":"CQ2：IV-to-oral転換 — 3条件と菌血症合併の扱い","url":"pages/articles-gl-uti-idsa2025.html#uti-cq2-rec","desc":"IDSA 2025 CQ2 › IV-to-oral転換","keywords":"IV-to-oral 早期経口転換 菌血症 bacteremia 3条件 臨床改善 経口摂取 有効な経口薬 BALANCE試験 von Dach 入院期間短縮 IVカテーテル"},
  {"title":"CQ3：投与期間 — FQ/非FQ/菌血症合併","url":"pages/articles-gl-uti-idsa2025.html#uti-cq3-rec","desc":"IDSA 2025 CQ3 › 投与期間","keywords":"投与期間 5-7日 7日 菌血症合併 グラム陰性菌血症 10-14日 不要 メタ解析 2945例 非劣性 フルオロキノロン FQ 非FQ 臨床的治癒率"},
  {"title":"男性のcUTI・前立腺炎・臨床改善なし時の対応","url":"pages/articles-gl-uti-idsa2025.html#uti-special","desc":"IDSA 2025 CQ3 › 特殊状況","keywords":"男性 前立腺炎 10-14日 前立腺移行性 FQ TMP-SMX ニトロフラントイン 不適 drug-bug mismatch 感染源コントロール 他の診断 発熱"},

  // ── 重症患者の栄養再考（ICM 2024, Stoppe et al.）──
  {"title":"重症患者の栄養を再考する — エネルギー・タンパク質投与の最新エビデンス（ICM 2024）","url":"pages/articles-gl-stoppe-nutrition2024.html","desc":"Intensive Care Med 2024 › 概要","keywords":"栄養 エネルギー タンパク質 段階的栄養 過剰栄養 低栄養 AKI 急性腎障害 リフィーディング 間接熱量測定 IC PRECISe EFFORT NUTRIREA-3 プロポフォール デキストロース クエン酸 非栄養エネルギー ICU 重症患者 Stoppe Ridley Lee"},
  {"title":"エネルギー投与量 — 9つのランドマークRCTの概要","url":"pages/articles-gl-stoppe-nutrition2024.html#stoppe-ch1","desc":"ICM 2024 › エネルギー投与量","keywords":"エネルギー kcal/kg ランドマークRCT 間接熱量測定 APACHE II SOFA 高エネルギー 低エネルギー 臓器機能障害 消化管不耐 血糖 リン 感染症"},
  {"title":"高エネルギー投与の有害アウトカム一覧","url":"pages/articles-gl-stoppe-nutrition2024.html#stoppe-s2","desc":"ICM 2024 › 高エネルギーの弊害","keywords":"高エネルギー 有害 臓器機能障害 腎 肝 肺 消化管不耐 逆流 嘔吐 便秘 下痢 腸管虚血 血糖上昇 インスリン リン 感染症"},
  {"title":"タンパク質投与量 — 23RCT・3303例のメタ解析","url":"pages/articles-gl-stoppe-nutrition2024.html#stoppe-ch2","desc":"ICM 2024 › タンパク質投与量","keywords":"タンパク質 protein メタ解析 RCT 高タンパク 低タンパク AKI 死亡率 筋肉量 身体機能 PRECISe EQ-5D QOL 機能回復"},
  {"title":"段階的栄養投与アルゴリズム（ICU日数別目標値）","url":"pages/articles-gl-stoppe-nutrition2024.html#stoppe-s6","desc":"ICM 2024 › 段階的栄養投与","keywords":"段階的栄養 day 1-4 day 5-7 day 7超 5-10 kcal 15-20 kcal 20-25 kcal 0.2-0.6 g/kg 0.8-1.0 g/kg 1.0-1.2 g/kg 維持量 低用量 昇圧剤 臓器サポート 微量栄養素"},
  {"title":"エネルギー・タンパク質の減量トリガー（モニタリング指標）","url":"pages/articles-gl-stoppe-nutrition2024.html#stoppe-s7","desc":"ICM 2024 › 減量トリガー","keywords":"リン酸 0.16 mmol/L 0.65 mmol/L 72時間 リフィーディング 血糖 10 mmol/L インスリン トリグリセリド 4.5 mmol/L 尿素 クレアチニン AKI 腎代替療法 0.8 g/kg 非栄養エネルギー プロポフォール デキストロース クエン酸"},

  // ── ペラミビル（Drugs 2018）──
  {"title":"ペラミビル（Rapiacta®）レビュー — 非重症インフルエンザ","url":"pages/articles-gl-peramivir2018.html","desc":"Drugs 2018 › 概要","keywords":"ペラミビル peramivir Rapiacta Rapivab Alpivab インフルエンザ influenza NAI ノイラミニダーゼ阻害薬 静注 単回投与 オセルタミビル 非劣性"},
  {"title":"ペラミビルの薬理学的特性（作用機序・耐性・PK）","url":"pages/articles-gl-peramivir2018.html#pera-ch1","desc":"Drugs 2018 › 第1章","keywords":"ノイラミニダーゼ NA シクロペンタン H275Y 耐性 GISRS サーベイランス 薬物動態 PK 線形 腎排泄 気道上皮"},
  {"title":"作用機序と抗ウイルス活性（ペラミビル）","url":"pages/articles-gl-peramivir2018.html#pera1-s1","desc":"Drugs 2018 第1章 › SECTION 1","keywords":"ノイラミニダーゼ阻害 シアル酸 シクロペンタン 5員環 耐性 RI HRI H275Y クロス耐性 GISRS 1%未満"},
  {"title":"薬物動態 — ペラミビルのPKプロファイル","url":"pages/articles-gl-peramivir2018.html#pera1-s2","desc":"Drugs 2018 第1章 › SECTION 2","keywords":"薬物動態 PK 線形 用量比例 分布容積 タンパク結合 腎排泄 半減期 気道上皮ライニング液 腎機能低下 用量調整"},
  {"title":"ペラミビルの臨床的有効性（成人・小児）","url":"pages/articles-gl-peramivir2018.html#pera-ch2","desc":"Drugs 2018 › 第2章","keywords":"有効性 第3相試験 成人 小児 症状消失 プラセボ対照 オセルタミビル 非劣性 解熱 サブタイプ A/H1N1 A/H3N2"},
  {"title":"成人における有効性（Kohno 2010/2011試験）","url":"pages/articles-gl-peramivir2018.html#pera2-s1","desc":"Drugs 2018 第2章 › SECTION 1","keywords":"Kohno 2010 2011 プラセボ オセルタミビル 非劣性 症状消失 59.9時間 81.8時間 解熱 A/H3N2 HR 0.666 単回投与"},
  {"title":"小児における有効性（ペラミビル）","url":"pages/articles-gl-peramivir2018.html#pera2-s2","desc":"Drugs 2018 第2章 › SECTION 2","keywords":"小児 2歳 12mg/kg 600mg 最大 中間解析 75.6時間 IDWeek 2017 解熱 2〜12歳 13〜17歳"},
  {"title":"ペラミビルの安全性・用量・臨床的位置づけ","url":"pages/articles-gl-peramivir2018.html#pera-ch3","desc":"Drugs 2018 › 第3章","keywords":"安全性 副反応 好中球減少 悪心 TEN SJS 神経精神症状 腎障害 600mg 単回 15-30分 48時間以内"},
  {"title":"忍容性と有害事象（ペラミビル）","url":"pages/articles-gl-peramivir2018.html#pera3-s1","desc":"Drugs 2018 第3章 › SECTION 1","keywords":"副反応 好中球減少 悪心 下痢 軽度 中等度 TEN SJS 多形性紅斑 神経精神症状 せん妄 幻覚 腎障害 小児 発疹 発熱"},
  {"title":"投与方法と用量（ペラミビル）","url":"pages/articles-gl-peramivir2018.html#pera3-s2","desc":"Drugs 2018 第3章 › SECTION 2","keywords":"用量 600mg 12mg/kg 最大600mg 15-30分 48時間以内 2歳以上 腎機能低下 B型 重症 非推奨"},
  {"title":"ペラミビルの強みと使い分け（NAI3剤比較）","url":"pages/articles-gl-peramivir2018.html#pera4-s1","desc":"Drugs 2018 第4章 › SECTION 1","keywords":"NAI比較 オセルタミビル ザナミビル 静注 単回 嘔吐 嚥下困難 アドヒアランス 2歳以上 気管支痙攣 吸入 高リスク"},

  // ── ストレス潰瘍予防 H2RA vs PPI（Crit Care Med 2025）──
  {"title":"ストレス潰瘍予防 H2RA vs PPI — 敗血症性ショック患者における比較（Crit Care Med 2025）","url":"pages/articles-gl-sup-septicshock2025.html","desc":"220病院・15,102例の後ろ向き多施設IPTW解析。PPIはH2RAと比較してUGIB発生率を有意に低下（OR 0.78）。死亡率・VAP・CDI・在院日数は差なし。","keywords":"ストレス潰瘍 stress ulcer SUP ストレス潰瘍予防 H2RA H2受容体拮抗薬 PPI プロトンポンプ阻害薬 ファモチジン famotidine パントプラゾール pantoprazole 上部消化管出血 UGIB gastrointestinal bleeding 敗血症性ショック septic shock IPTW propensity 院内死亡 VAP 人工呼吸器関連肺炎 C. difficile CDI PEPTIC REVISE Patanwala Erstad Critical Care Medicine 2025"},
  {"title":"SUP H2RA vs PPI — 研究背景（PEPTIC・REVISE・ガイドライン）","url":"pages/articles-gl-sup-septicshock2025.html#background","desc":"SCCM/ASHP 2024ガイドラインの推奨とPEPTIC・REVISE試験の限界、敗血症性ショックに特化したSUP研究の必要性","keywords":"PEPTIC試験 REVISE試験 SCCM ASHP ガイドライン 条件付き推奨 ネットワークメタ解析 死亡率 UGIBリスク ショック 消化管低灌流"},
  {"title":"SUP H2RA vs PPI — デザイン・患者背景（15,102例）","url":"pages/articles-gl-sup-septicshock2025.html#design","desc":"220病院のPINC AI Databaseを使用。敗血症性ショック（ICD-10 R65.21 + 昇圧薬）。IPTW調整後SMD<0.1","keywords":"PINC AI Healthcare Database Premier 後ろ向きコホート 多施設 220病院 IPTW 逆確率治療重み付け SMD APACHE II STROBE 敗血症性ショック ICD-10 R65.21 昇圧薬"},
  {"title":"SUP H2RA vs PPI — 主要アウトカム：UGIB（OR 0.78）","url":"pages/articles-gl-sup-septicshock2025.html#primary-outcome","desc":"UGIB発生率：H2RA 3.6% vs PPI 3.0%（OR 0.78; 95% CI 0.64–0.96; p=0.016）。ファモチジン対パントプラゾール感度分析でも再現（OR 0.80; p=0.025）","keywords":"UGIB 上部消化管出血 OR 0.78 0.64 0.96 p=0.016 ファモチジン パントプラゾール 感度分析 3.6% 3.0% 絶対差 0.6%"},
  {"title":"SUP H2RA vs PPI — 副次アウトカム：死亡率・VAP・CDI・在院日数","url":"pages/articles-gl-sup-septicshock2025.html#secondary-outcomes","desc":"院内死亡率33.4% vs 33.3%（NS）、VAP 13.3% vs 13.3%（NS）、C. difficile 0.5% vs 0.6%（NS）、在院日数7日 vs 8日（NS）","keywords":"院内死亡率 33% VAP 人工呼吸器関連肺炎 13.3% C. difficile CDI 0.5% 0.6% 在院日数 7日 8日 OR 0.98 0.93 1.32 IRR 1.01"},
  {"title":"SUP H2RA vs PPI — サブグループ：年齢・APACHE IIで交互作用","url":"pages/articles-gl-sup-septicshock2025.html#subgroup","desc":"年齢<65歳（OR 0.63）とAPACHE II<25（OR 0.65）でPPIの優位性が顕著。高齢・高重症度では差が縮小","keywords":"サブグループ 年齢 65歳 APACHE II 25 交互作用 interaction p=0.015 p=0.038 若年 低重症度 高齢 高重症度 effect modification 肝疾患 凝固障害 IMV 性別"}
];
